// Generated by protocol/generate.mjs. Do not edit.
#pragma once
#include <string_view>

namespace rctl {
inline constexpr std::string_view guestPermissionIDs[] = {
    "screen.view",
    "input.touch",
    "input.keyboard",
    "input.button.home",
    "input.button.lock",
    "input.button.volume",
    "input.button.system_ui",
};
}
