// Generated by Tools/icons/generate-icons.mjs. Do not edit.
//
// Geometry derived from Lucide icons (lucide-react 0.469.0, https://lucide.dev),
// ISC License. See THIRD_PARTY_NOTICES.md for the full license notice.

import CoreGraphics

/// Lucide glyphs used by the app. Raw value = Lucide icon name.
enum RCIconGlyph: String, CaseIterable, Sendable {
    case activity = "activity"
    case appWindow = "app-window"
    case arrowBigUp = "arrow-big-up"
    case arrowDown = "arrow-down"
    case arrowDownToLine = "arrow-down-to-line"
    case arrowLeft = "arrow-left"
    case arrowLeftRight = "arrow-left-right"
    case arrowLeftToLine = "arrow-left-to-line"
    case arrowRight = "arrow-right"
    case arrowRightToLine = "arrow-right-to-line"
    case arrowUp = "arrow-up"
    case badgeCheck = "badge-check"
    case bell = "bell"
    case camera = "camera"
    case cameraOff = "camera-off"
    case cast = "cast"
    case check = "check"
    case chevronDown = "chevron-down"
    case chevronLeft = "chevron-left"
    case chevronRight = "chevron-right"
    case chevronUp = "chevron-up"
    case circle = "circle"
    case circleAlert = "circle-alert"
    case circleCheck = "circle-check"
    case circleCheckBig = "circle-check-big"
    case circleDot = "circle-dot"
    case circleHelp = "circle-help"
    case circleStop = "circle-stop"
    case circleX = "circle-x"
    case clipboard = "clipboard"
    case clipboardPaste = "clipboard-paste"
    case command = "command"
    case copy = "copy"
    case cornerDownLeft = "corner-down-left"
    case cpu = "cpu"
    case delete = "delete"
    case download = "download"
    case earth = "earth"
    case ellipsis = "ellipsis"
    case ellipsisVertical = "ellipsis-vertical"
    case externalLink = "external-link"
    case eye = "eye"
    case eyeOff = "eye-off"
    case fingerprint = "fingerprint"
    case flashlight = "flashlight"
    case flashlightOff = "flashlight-off"
    case gauge = "gauge"
    case globe = "globe"
    case gripHorizontal = "grip-horizontal"
    case hand = "hand"
    case hardDrive = "hard-drive"
    case history = "history"
    case house = "house"
    case info = "info"
    case keyRound = "key-round"
    case keyboard = "keyboard"
    case keyboardOff = "keyboard-off"
    case layers = "layers"
    case layoutPanelTop = "layout-panel-top"
    case lightbulb = "lightbulb"
    case lightbulbOff = "lightbulb-off"
    case link = "link"
    case listRestart = "list-restart"
    case loaderCircle = "loader-circle"
    case lock = "lock"
    case lockOpen = "lock-open"
    case logOut = "log-out"
    case maximize2 = "maximize-2"
    case mic = "mic"
    case micOff = "mic-off"
    case minimize2 = "minimize-2"
    case minus = "minus"
    case monitor = "monitor"
    case monitorSmartphone = "monitor-smartphone"
    case moon = "moon"
    case mousePointer2 = "mouse-pointer-2"
    case mousePointerClick = "mouse-pointer-click"
    case move = "move"
    case network = "network"
    case octagonX = "octagon-x"
    case option = "option"
    case palette = "palette"
    case panelBottom = "panel-bottom"
    case panelTop = "panel-top"
    case pencil = "pencil"
    case plugZap = "plug-zap"
    case plus = "plus"
    case pointer = "pointer"
    case power = "power"
    case qrCode = "qr-code"
    case radar = "radar"
    case radioTower = "radio-tower"
    case rectangleHorizontal = "rectangle-horizontal"
    case refreshCw = "refresh-cw"
    case `repeat` = "repeat"
    case rotateCcw = "rotate-ccw"
    case rotateCw = "rotate-cw"
    case router = "router"
    case satelliteDish = "satellite-dish"
    case save = "save"
    case scan = "scan"
    case scanEye = "scan-eye"
    case scanLine = "scan-line"
    case scanQrCode = "scan-qr-code"
    case scanText = "scan-text"
    case screenShare = "screen-share"
    case search = "search"
    case server = "server"
    case settings = "settings"
    case shieldAlert = "shield-alert"
    case shieldCheck = "shield-check"
    case signal = "signal"
    case slidersHorizontal = "sliders-horizontal"
    case smartphone = "smartphone"
    case sparkles = "sparkles"
    case squareDashed = "square-dashed"
    case squarePen = "square-pen"
    case sun = "sun"
    case sunMoon = "sun-moon"
    case tablet = "tablet"
    case tabletSmartphone = "tablet-smartphone"
    case tag = "tag"
    case textCursorInput = "text-cursor-input"
    case toggleRight = "toggle-right"
    case touchpad = "touchpad"
    case trash2 = "trash-2"
    case triangleAlert = "triangle-alert"
    case tv = "tv"
    case type = "type"
    case undo2 = "undo-2"
    case unplug = "unplug"
    case user = "user"
    case users = "users"
    case vibrate = "vibrate"
    case video = "video"
    case videoOff = "video-off"
    case volume1 = "volume-1"
    case volume2 = "volume-2"
    case volumeX = "volume-x"
    case wifi = "wifi"
    case wifiHigh = "wifi-high"
    case wifiOff = "wifi-off"
    case x = "x"
    case zap = "zap"
}

extension RCIconGlyph {
    /// Stroke geometry in Lucide's 24×24 viewBox (y down, UIKit orientation).
    func makePath() -> CGPath {
        let p = RCIconPathBuilder()
        switch self {
        case .activity:
            p.move(22, 12); p.line(19.52, 12); p.curve(18.6218, 11.9981, 17.8325, 12.5952, 17.59, 13.46);
            p.line(15.24, 21.82); p.curve(15.2089, 21.9267, 15.1111, 22, 15, 22);
            p.curve(14.8889, 22, 14.7911, 21.9267, 14.76, 21.82); p.line(9.24, 2.18);
            p.curve(9.2089, 2.0733, 9.1111, 2, 9, 2); p.curve(8.8889, 2, 8.7911, 2.0733, 8.76, 2.18);
            p.line(6.41, 10.54); p.curve(6.1685, 11.4013, 5.3845, 11.9974, 4.49, 12); p.line(2, 12);
        case .appWindow:
            p.move(4, 4); p.line(20, 4); p.curve(21.1046, 4, 22, 4.8954, 22, 6); p.line(22, 18);
            p.curve(22, 19.1046, 21.1046, 20, 20, 20); p.line(4, 20); p.curve(2.8954, 20, 2, 19.1046, 2, 18);
            p.line(2, 6); p.curve(2, 4.8954, 2.8954, 4, 4, 4); p.close();
            p.move(10, 4); p.line(10, 8);
            p.move(2, 8); p.line(22, 8);
            p.move(6, 4); p.line(6, 8);
        case .arrowBigUp:
            p.move(9, 18); p.line(9, 12); p.line(5, 12); p.line(12, 5); p.line(19, 12); p.line(15, 12); p.line(15, 18);
            p.line(9, 18); p.close();
        case .arrowDown:
            p.move(12, 5); p.line(12, 19);
            p.move(19, 12); p.line(12, 19); p.line(5, 12);
        case .arrowDownToLine:
            p.move(12, 17); p.line(12, 3);
            p.move(6, 11); p.line(12, 17); p.line(18, 11);
            p.move(19, 21); p.line(5, 21);
        case .arrowLeft:
            p.move(12, 19); p.line(5, 12); p.line(12, 5);
            p.move(19, 12); p.line(5, 12);
        case .arrowLeftRight:
            p.move(8, 3); p.line(4, 7); p.line(8, 11);
            p.move(4, 7); p.line(20, 7);
            p.move(16, 21); p.line(20, 17); p.line(16, 13);
            p.move(20, 17); p.line(4, 17);
        case .arrowLeftToLine:
            p.move(3, 19); p.line(3, 5);
            p.move(13, 6); p.line(7, 12); p.line(13, 18);
            p.move(7, 12); p.line(21, 12);
        case .arrowRight:
            p.move(5, 12); p.line(19, 12);
            p.move(12, 5); p.line(19, 12); p.line(12, 19);
        case .arrowRightToLine:
            p.move(17, 12); p.line(3, 12);
            p.move(11, 18); p.line(17, 12); p.line(11, 6);
            p.move(21, 5); p.line(21, 19);
        case .arrowUp:
            p.move(5, 12); p.line(12, 5); p.line(19, 12);
            p.move(12, 19); p.line(12, 5);
        case .badgeCheck:
            p.move(3.85, 8.62); p.curve(3.5534, 7.2837, 3.9606, 5.8886, 4.9295, 4.9217);
            p.curve(5.8984, 3.9549, 7.2944, 3.5506, 8.63, 3.85); p.curve(9.3651, 2.7004, 10.6355, 2.0048, 12, 2.0048);
            p.curve(13.3645, 2.0048, 14.6349, 2.7004, 15.37, 3.85);
            p.curve(16.7077, 3.5492, 18.1063, 3.9546, 19.0758, 4.9242);
            p.curve(20.0454, 5.8937, 20.4508, 7.2923, 20.15, 8.63);
            p.curve(21.2996, 9.3651, 21.9952, 10.6355, 21.9952, 12);
            p.curve(21.9952, 13.3645, 21.2996, 14.6349, 20.15, 15.37);
            p.curve(20.4494, 16.7056, 20.0451, 18.1016, 19.0783, 19.0705);
            p.curve(18.1114, 20.0394, 16.7163, 20.4466, 15.38, 20.15);
            p.curve(14.6458, 21.3041, 13.3728, 22.0031, 12.005, 22.0031);
            p.curve(10.6372, 22.0031, 9.3642, 21.3041, 8.63, 20.15);
            p.curve(7.2944, 20.4494, 5.8984, 20.0451, 4.9295, 19.0783);
            p.curve(3.9606, 18.1114, 3.5534, 16.7163, 3.85, 15.38);
            p.curve(2.6914, 14.6468, 1.9891, 13.3712, 1.9891, 12); p.curve(1.9891, 10.6288, 2.6914, 9.3532, 3.85, 8.62);
            p.close();
            p.move(9, 12); p.line(11, 14); p.line(15, 10);
        case .bell:
            p.move(10.268, 21); p.curve(10.6253, 21.6188, 11.2855, 21.9999, 12, 21.9999);
            p.curve(12.7145, 21.9999, 13.3747, 21.6188, 13.732, 21);
            p.move(3.262, 15.326); p.curve(2.9951, 15.6185, 2.926, 16.041, 3.0857, 16.4034);
            p.curve(3.2455, 16.7658, 3.604, 16.9997, 4, 17); p.line(20, 17);
            p.curve(20.396, 17.0001, 20.7547, 16.7666, 20.9149, 16.4045);
            p.curve(21.0751, 16.0424, 21.0065, 15.6199, 20.74, 15.327); p.curve(19.41, 13.956, 18, 12.499, 18, 8);
            p.curve(18, 4.6863, 15.3137, 2, 12, 2); p.curve(8.6863, 2, 6, 4.6863, 6, 8);
            p.curve(6, 12.499, 4.589, 13.956, 3.262, 15.326);
        case .camera:
            p.move(14.5, 4); p.line(9.5, 4); p.line(7, 7); p.line(4, 7); p.curve(2.8954, 7, 2, 7.8954, 2, 9);
            p.line(2, 18); p.curve(2, 19.1046, 2.8954, 20, 4, 20); p.line(20, 20);
            p.curve(21.1046, 20, 22, 19.1046, 22, 18); p.line(22, 9); p.curve(22, 7.8954, 21.1046, 7, 20, 7);
            p.line(17, 7); p.line(14.5, 4); p.close();
            p.move(15, 13); p.curve(15, 14.6569, 13.6569, 16, 12, 16); p.curve(10.3431, 16, 9, 14.6569, 9, 13);
            p.curve(9, 11.3431, 10.3431, 10, 12, 10); p.curve(13.6569, 10, 15, 11.3431, 15, 13); p.close();
        case .cameraOff:
            p.move(2, 2); p.line(22, 22);
            p.move(7, 7); p.line(4, 7); p.curve(2.8954, 7, 2, 7.8954, 2, 9); p.line(2, 18);
            p.curve(2, 19.1046, 2.8954, 20, 4, 20); p.line(20, 20);
            p.move(9.5, 4); p.line(14.5, 4); p.line(17, 7); p.line(20, 7); p.curve(21.1046, 7, 22, 7.8954, 22, 9);
            p.line(22, 16.5);
            p.move(14.121, 15.121); p.curve(13.3708, 15.9141, 12.249, 16.2371, 11.192, 15.9643);
            p.curve(10.1349, 15.6916, 9.3094, 14.8661, 9.0367, 13.809);
            p.curve(8.7639, 12.752, 9.0869, 11.6302, 9.88, 10.88);
        case .cast:
            p.move(2, 8); p.line(2, 6); p.curve(2, 4.8954, 2.8954, 4, 4, 4); p.line(20, 4);
            p.curve(21.1046, 4, 22, 4.8954, 22, 6); p.line(22, 18); p.curve(22, 19.1046, 21.1046, 20, 20, 20);
            p.line(14, 20);
            p.move(2, 12); p.curve(6.219, 12.4477, 9.5523, 15.781, 10, 20);
            p.move(2, 16); p.curve(4.0319, 16.3784, 5.6216, 17.9681, 6, 20);
            p.move(2, 20); p.line(2.01, 20);
        case .check:
            p.move(20, 6); p.line(9, 17); p.line(4, 12);
        case .chevronDown:
            p.move(6, 9); p.line(12, 15); p.line(18, 9);
        case .chevronLeft:
            p.move(15, 18); p.line(9, 12); p.line(15, 6);
        case .chevronRight:
            p.move(9, 18); p.line(15, 12); p.line(9, 6);
        case .chevronUp:
            p.move(18, 15); p.line(12, 9); p.line(6, 15);
        case .circle:
            p.move(22, 12); p.curve(22, 17.5228, 17.5228, 22, 12, 22); p.curve(6.4772, 22, 2, 17.5228, 2, 12);
            p.curve(2, 6.4772, 6.4772, 2, 12, 2); p.curve(17.5228, 2, 22, 6.4772, 22, 12); p.close();
        case .circleAlert:
            p.move(22, 12); p.curve(22, 17.5228, 17.5228, 22, 12, 22); p.curve(6.4772, 22, 2, 17.5228, 2, 12);
            p.curve(2, 6.4772, 6.4772, 2, 12, 2); p.curve(17.5228, 2, 22, 6.4772, 22, 12); p.close();
            p.move(12, 8); p.line(12, 12);
            p.move(12, 16); p.line(12.01, 16);
        case .circleCheck:
            p.move(22, 12); p.curve(22, 17.5228, 17.5228, 22, 12, 22); p.curve(6.4772, 22, 2, 17.5228, 2, 12);
            p.curve(2, 6.4772, 6.4772, 2, 12, 2); p.curve(17.5228, 2, 22, 6.4772, 22, 12); p.close();
            p.move(9, 12); p.line(11, 14); p.line(15, 10);
        case .circleCheckBig:
            p.move(21.801, 10); p.curve(22.7421, 14.6185, 20.3303, 19.2672, 16.0125, 21.1573);
            p.curve(11.6947, 23.0475, 6.6432, 21.6659, 3.8883, 17.8414);
            p.curve(1.1334, 14.0169, 1.4231, 8.7879, 4.5837, 5.2912);
            p.curve(7.7442, 1.7944, 12.9174, 0.9794, 17, 3.335);
            p.move(9, 11); p.line(12, 14); p.line(22, 4);
        case .circleDot:
            p.move(22, 12); p.curve(22, 17.5228, 17.5228, 22, 12, 22); p.curve(6.4772, 22, 2, 17.5228, 2, 12);
            p.curve(2, 6.4772, 6.4772, 2, 12, 2); p.curve(17.5228, 2, 22, 6.4772, 22, 12); p.close();
            p.move(13, 12); p.curve(13, 12.5523, 12.5523, 13, 12, 13); p.curve(11.4477, 13, 11, 12.5523, 11, 12);
            p.curve(11, 11.4477, 11.4477, 11, 12, 11); p.curve(12.5523, 11, 13, 11.4477, 13, 12); p.close();
        case .circleHelp:
            p.move(22, 12); p.curve(22, 17.5228, 17.5228, 22, 12, 22); p.curve(6.4772, 22, 2, 17.5228, 2, 12);
            p.curve(2, 6.4772, 6.4772, 2, 12, 2); p.curve(17.5228, 2, 22, 6.4772, 22, 12); p.close();
            p.move(9.09, 9); p.curve(9.5754, 7.62, 10.9854, 6.7914, 12.4272, 7.0387);
            p.curve(13.869, 7.286, 14.9222, 8.5372, 14.92, 10); p.curve(14.92, 12, 11.92, 13, 11.92, 13);
            p.move(12, 17); p.line(12.01, 17);
        case .circleStop:
            p.move(22, 12); p.curve(22, 17.5228, 17.5228, 22, 12, 22); p.curve(6.4772, 22, 2, 17.5228, 2, 12);
            p.curve(2, 6.4772, 6.4772, 2, 12, 2); p.curve(17.5228, 2, 22, 6.4772, 22, 12); p.close();
            p.move(10, 9); p.line(14, 9); p.curve(14.5523, 9, 15, 9.4477, 15, 10); p.line(15, 14);
            p.curve(15, 14.5523, 14.5523, 15, 14, 15); p.line(10, 15); p.curve(9.4477, 15, 9, 14.5523, 9, 14);
            p.line(9, 10); p.curve(9, 9.4477, 9.4477, 9, 10, 9); p.close();
        case .circleX:
            p.move(22, 12); p.curve(22, 17.5228, 17.5228, 22, 12, 22); p.curve(6.4772, 22, 2, 17.5228, 2, 12);
            p.curve(2, 6.4772, 6.4772, 2, 12, 2); p.curve(17.5228, 2, 22, 6.4772, 22, 12); p.close();
            p.move(15, 9); p.line(9, 15);
            p.move(9, 9); p.line(15, 15);
        case .clipboard:
            p.move(9, 2); p.line(15, 2); p.curve(15.5523, 2, 16, 2.4477, 16, 3); p.line(16, 5);
            p.curve(16, 5.5523, 15.5523, 6, 15, 6); p.line(9, 6); p.curve(8.4477, 6, 8, 5.5523, 8, 5); p.line(8, 3);
            p.curve(8, 2.4477, 8.4477, 2, 9, 2); p.close();
            p.move(16, 4); p.line(18, 4); p.curve(19.1046, 4, 20, 4.8954, 20, 6); p.line(20, 20);
            p.curve(20, 21.1046, 19.1046, 22, 18, 22); p.line(6, 22); p.curve(4.8954, 22, 4, 21.1046, 4, 20);
            p.line(4, 6); p.curve(4, 4.8954, 4.8954, 4, 6, 4); p.line(8, 4);
        case .clipboardPaste:
            p.move(15, 2); p.line(9, 2); p.curve(8.4477, 2, 8, 2.4477, 8, 3); p.line(8, 5);
            p.curve(8, 5.6, 8.4, 6, 9, 6); p.line(15, 6); p.curve(15.6, 6, 16, 5.6, 16, 5); p.line(16, 3);
            p.curve(16, 2.4, 15.6, 2, 15, 2); p.close();
            p.move(8, 4); p.line(6, 4); p.curve(4.8954, 4, 4, 4.8954, 4, 6); p.line(4, 20);
            p.curve(4, 21.1046, 4.8954, 22, 6, 22); p.line(18, 22); p.curve(19.1046, 22, 20, 21.1046, 20, 20);
            p.move(16, 4); p.line(18, 4); p.curve(19.1046, 4, 20, 4.8954, 20, 6); p.line(20, 8); p.move(11, 14);
            p.line(21, 14);
            p.move(17, 10); p.line(21, 14); p.line(17, 18);
        case .command:
            p.move(15, 6); p.line(15, 18); p.curve(15, 19.6569, 16.3431, 21, 18, 21);
            p.curve(19.6569, 21, 21, 19.6569, 21, 18); p.curve(21, 16.3431, 19.6569, 15, 18, 15); p.line(6, 15);
            p.curve(4.3431, 15, 3, 16.3431, 3, 18); p.curve(3, 19.6569, 4.3431, 21, 6, 21);
            p.curve(7.6569, 21, 9, 19.6569, 9, 18); p.line(9, 6); p.curve(9, 4.3431, 7.6569, 3, 6, 3);
            p.curve(4.3431, 3, 3, 4.3431, 3, 6); p.curve(3, 7.6569, 4.3431, 9, 6, 9); p.line(18, 9);
            p.curve(19.6569, 9, 21, 7.6569, 21, 6); p.curve(21, 4.3431, 19.6569, 3, 18, 3);
            p.curve(16.3431, 3, 15, 4.3431, 15, 6);
        case .copy:
            p.move(10, 8); p.line(20, 8); p.curve(21.1046, 8, 22, 8.8954, 22, 10); p.line(22, 20);
            p.curve(22, 21.1046, 21.1046, 22, 20, 22); p.line(10, 22); p.curve(8.8954, 22, 8, 21.1046, 8, 20);
            p.line(8, 10); p.curve(8, 8.8954, 8.8954, 8, 10, 8); p.close();
            p.move(4, 16); p.curve(2.9, 16, 2, 15.1, 2, 14); p.line(2, 4); p.curve(2, 2.9, 2.9, 2, 4, 2); p.line(14, 2);
            p.curve(15.1, 2, 16, 2.9, 16, 4);
        case .cornerDownLeft:
            p.move(9, 10); p.line(4, 15); p.line(9, 20);
            p.move(20, 4); p.line(20, 11); p.curve(20, 13.2091, 18.2091, 15, 16, 15); p.line(4, 15);
        case .cpu:
            p.move(6, 4); p.line(18, 4); p.curve(19.1046, 4, 20, 4.8954, 20, 6); p.line(20, 18);
            p.curve(20, 19.1046, 19.1046, 20, 18, 20); p.line(6, 20); p.curve(4.8954, 20, 4, 19.1046, 4, 18);
            p.line(4, 6); p.curve(4, 4.8954, 4.8954, 4, 6, 4); p.close();
            p.move(10, 9); p.line(14, 9); p.curve(14.5523, 9, 15, 9.4477, 15, 10); p.line(15, 14);
            p.curve(15, 14.5523, 14.5523, 15, 14, 15); p.line(10, 15); p.curve(9.4477, 15, 9, 14.5523, 9, 14);
            p.line(9, 10); p.curve(9, 9.4477, 9.4477, 9, 10, 9); p.close();
            p.move(15, 2); p.line(15, 4);
            p.move(15, 20); p.line(15, 22);
            p.move(2, 15); p.line(4, 15);
            p.move(2, 9); p.line(4, 9);
            p.move(20, 15); p.line(22, 15);
            p.move(20, 9); p.line(22, 9);
            p.move(9, 2); p.line(9, 4);
            p.move(9, 20); p.line(9, 22);
        case .delete:
            p.move(10, 5); p.curve(9.5031, 5, 9.024, 5.185, 8.656, 5.519); p.line(2.328, 11.259);
            p.curve(2.1192, 11.4485, 2.0001, 11.7175, 2.0001, 11.9995);
            p.curve(2.0001, 12.2815, 2.1192, 12.5505, 2.328, 12.74); p.line(8.656, 18.481);
            p.curve(9.024, 18.815, 9.5031, 19, 10, 19); p.line(20, 19); p.curve(21.1046, 19, 22, 18.1046, 22, 17);
            p.line(22, 7); p.curve(22, 5.8954, 21.1046, 5, 20, 5); p.close();
            p.move(12, 9); p.line(18, 15);
            p.move(18, 9); p.line(12, 15);
        case .download:
            p.move(21, 15); p.line(21, 19); p.curve(21, 20.1046, 20.1046, 21, 19, 21); p.line(5, 21);
            p.curve(3.8954, 21, 3, 20.1046, 3, 19); p.line(3, 15);
            p.move(7, 10); p.line(12, 15); p.line(17, 10);
            p.move(12, 15); p.line(12, 3);
        case .earth:
            p.move(21.54, 15); p.line(17, 15); p.curve(15.8954, 15, 15, 15.8954, 15, 17); p.line(15, 21.54);
            p.move(7, 3.34); p.line(7, 5); p.curve(7, 6.6569, 8.3431, 8, 10, 8);
            p.curve(11.1046, 8, 12, 8.8954, 12, 10); p.curve(12, 11.1, 12.9, 12, 14, 12);
            p.curve(15.1046, 12, 16, 11.1046, 16, 10); p.curve(16, 8.9, 16.9, 8, 18, 8); p.line(21.17, 8);
            p.move(11, 21.95); p.line(11, 18); p.curve(11, 16.8954, 10.1046, 16, 9, 16);
            p.curve(7.8954, 16, 7, 15.1046, 7, 14); p.line(7, 13); p.curve(7, 11.8954, 6.1046, 11, 5, 11);
            p.line(2.05, 11);
            p.move(22, 12); p.curve(22, 17.5228, 17.5228, 22, 12, 22); p.curve(6.4772, 22, 2, 17.5228, 2, 12);
            p.curve(2, 6.4772, 6.4772, 2, 12, 2); p.curve(17.5228, 2, 22, 6.4772, 22, 12); p.close();
        case .ellipsis:
            p.move(13, 12); p.curve(13, 12.5523, 12.5523, 13, 12, 13); p.curve(11.4477, 13, 11, 12.5523, 11, 12);
            p.curve(11, 11.4477, 11.4477, 11, 12, 11); p.curve(12.5523, 11, 13, 11.4477, 13, 12); p.close();
            p.move(20, 12); p.curve(20, 12.5523, 19.5523, 13, 19, 13); p.curve(18.4477, 13, 18, 12.5523, 18, 12);
            p.curve(18, 11.4477, 18.4477, 11, 19, 11); p.curve(19.5523, 11, 20, 11.4477, 20, 12); p.close();
            p.move(6, 12); p.curve(6, 12.5523, 5.5523, 13, 5, 13); p.curve(4.4477, 13, 4, 12.5523, 4, 12);
            p.curve(4, 11.4477, 4.4477, 11, 5, 11); p.curve(5.5523, 11, 6, 11.4477, 6, 12); p.close();
        case .ellipsisVertical:
            p.move(13, 12); p.curve(13, 12.5523, 12.5523, 13, 12, 13); p.curve(11.4477, 13, 11, 12.5523, 11, 12);
            p.curve(11, 11.4477, 11.4477, 11, 12, 11); p.curve(12.5523, 11, 13, 11.4477, 13, 12); p.close();
            p.move(13, 5); p.curve(13, 5.5523, 12.5523, 6, 12, 6); p.curve(11.4477, 6, 11, 5.5523, 11, 5);
            p.curve(11, 4.4477, 11.4477, 4, 12, 4); p.curve(12.5523, 4, 13, 4.4477, 13, 5); p.close();
            p.move(13, 19); p.curve(13, 19.5523, 12.5523, 20, 12, 20); p.curve(11.4477, 20, 11, 19.5523, 11, 19);
            p.curve(11, 18.4477, 11.4477, 18, 12, 18); p.curve(12.5523, 18, 13, 18.4477, 13, 19); p.close();
        case .externalLink:
            p.move(15, 3); p.line(21, 3); p.line(21, 9);
            p.move(10, 14); p.line(21, 3);
            p.move(18, 13); p.line(18, 19); p.curve(18, 20.1046, 17.1046, 21, 16, 21); p.line(5, 21);
            p.curve(3.8954, 21, 3, 20.1046, 3, 19); p.line(3, 8); p.curve(3, 6.8954, 3.8954, 6, 5, 6); p.line(11, 6);
        case .eye:
            p.move(2.062, 12.348); p.curve(1.9787, 12.1235, 1.9787, 11.8765, 2.062, 11.652);
            p.curve(3.722, 7.6269, 7.646, 5.0006, 12, 5.0006); p.curve(16.354, 5.0006, 20.278, 7.6269, 21.938, 11.652);
            p.curve(22.0213, 11.8765, 22.0213, 12.1235, 21.938, 12.348);
            p.curve(20.278, 16.3731, 16.354, 18.9994, 12, 18.9994);
            p.curve(7.646, 18.9994, 3.722, 16.3731, 2.062, 12.348);
            p.move(15, 12); p.curve(15, 13.6569, 13.6569, 15, 12, 15); p.curve(10.3431, 15, 9, 13.6569, 9, 12);
            p.curve(9, 10.3431, 10.3431, 9, 12, 9); p.curve(13.6569, 9, 15, 10.3431, 15, 12); p.close();
        case .eyeOff:
            p.move(10.733, 5.076); p.curve(15.5201, 4.5055, 20.1012, 7.1936, 21.938, 11.651);
            p.curve(22.0213, 11.8755, 22.0213, 12.1225, 21.938, 12.347);
            p.curve(21.5705, 13.238, 21.0848, 14.0755, 20.494, 14.837);
            p.move(14.084, 14.158); p.curve(12.9069, 15.2949, 11.0357, 15.2787, 9.8785, 14.1215);
            p.curve(8.7213, 12.9643, 8.7051, 11.0931, 9.842, 9.916);
            p.move(17.479, 17.499); p.curve(14.7949, 19.0889, 11.5525, 19.4345, 8.5936, 18.4459);
            p.curve(5.6348, 17.4573, 3.2513, 15.2321, 2.062, 12.348);
            p.curve(1.9787, 12.1235, 1.9787, 11.8765, 2.062, 11.652);
            p.curve(2.9486, 9.5019, 4.5087, 7.6972, 6.508, 6.509);
            p.move(2, 2); p.line(22, 22);
        case .fingerprint:
            p.move(12, 10); p.curve(10.8954, 10, 10, 10.8954, 10, 12); p.curve(10, 13.02, 9.9, 14.51, 9.74, 16);
            p.move(14, 13.12); p.curve(14, 15.5, 14, 19.5, 13, 22);
            p.move(17.29, 21.02); p.curve(17.41, 20.42, 17.72, 18.72, 17.79, 18);
            p.move(2, 12); p.curve(2, 7.6957, 4.7543, 3.8743, 8.8377, 2.5132);
            p.curve(12.9211, 1.152, 17.4174, 2.5566, 20, 6);
            p.move(2, 16); p.line(2.01, 16);
            p.move(21.8, 16); p.curve(22, 14, 21.931, 10.646, 21.8, 10);
            p.move(5, 19.5); p.curve(5.5, 18, 6, 15, 6, 12); p.curve(5.999, 11.3189, 6.114, 10.6425, 6.34, 10);
            p.move(8.65, 22); p.curve(8.86, 21.34, 9.1, 20.68, 9.22, 20);
            p.move(9, 6.8); p.curve(10.857, 5.7279, 13.145, 5.7282, 15.0017, 6.801);
            p.curve(16.8583, 7.8737, 18.0014, 9.8557, 18, 12); p.line(18, 14);
        case .flashlight:
            p.move(18, 6); p.curve(18, 8, 16, 8, 16, 10); p.line(16, 20); p.curve(16, 21.1046, 15.1046, 22, 14, 22);
            p.line(10, 22); p.curve(8.8954, 22, 8, 21.1046, 8, 20); p.line(8, 10); p.curve(8, 8, 6, 8, 6, 6);
            p.line(6, 2); p.line(18, 2); p.close();
            p.move(6, 6); p.line(18, 6);
            p.move(12, 12); p.line(12, 12);
        case .flashlightOff:
            p.move(16, 16); p.line(16, 20); p.curve(16, 21.1046, 15.1046, 22, 14, 22); p.line(10, 22);
            p.curve(8.8954, 22, 8, 21.1046, 8, 20); p.line(8, 10); p.curve(8, 8, 6, 8, 6, 6);
            p.move(7, 2); p.line(18, 2); p.line(18, 6); p.curve(18, 8, 16, 8, 16, 10); p.line(16, 11);
            p.move(11, 6); p.line(18, 6);
            p.move(2, 2); p.line(22, 22);
        case .gauge:
            p.move(12, 14); p.line(16, 10);
            p.move(3.34, 19); p.curve(0.9133, 14.7972, 1.8544, 9.4588, 5.572, 6.3392);
            p.curve(9.2896, 3.2197, 14.7104, 3.2197, 18.428, 6.3392);
            p.curve(22.1456, 9.4588, 23.0867, 14.7972, 20.66, 19);
        case .globe:
            p.move(22, 12); p.curve(22, 17.5228, 17.5228, 22, 12, 22); p.curve(6.4772, 22, 2, 17.5228, 2, 12);
            p.curve(2, 6.4772, 6.4772, 2, 12, 2); p.curve(17.5228, 2, 22, 6.4772, 22, 12); p.close();
            p.move(12, 2); p.curve(6.6667, 7.6, 6.6667, 16.4, 12, 22); p.curve(17.3333, 16.4, 17.3333, 7.6, 12, 2);
            p.move(2, 12); p.line(22, 12);
        case .gripHorizontal:
            p.move(13, 9); p.curve(13, 9.5523, 12.5523, 10, 12, 10); p.curve(11.4477, 10, 11, 9.5523, 11, 9);
            p.curve(11, 8.4477, 11.4477, 8, 12, 8); p.curve(12.5523, 8, 13, 8.4477, 13, 9); p.close();
            p.move(20, 9); p.curve(20, 9.5523, 19.5523, 10, 19, 10); p.curve(18.4477, 10, 18, 9.5523, 18, 9);
            p.curve(18, 8.4477, 18.4477, 8, 19, 8); p.curve(19.5523, 8, 20, 8.4477, 20, 9); p.close();
            p.move(6, 9); p.curve(6, 9.5523, 5.5523, 10, 5, 10); p.curve(4.4477, 10, 4, 9.5523, 4, 9);
            p.curve(4, 8.4477, 4.4477, 8, 5, 8); p.curve(5.5523, 8, 6, 8.4477, 6, 9); p.close();
            p.move(13, 15); p.curve(13, 15.5523, 12.5523, 16, 12, 16); p.curve(11.4477, 16, 11, 15.5523, 11, 15);
            p.curve(11, 14.4477, 11.4477, 14, 12, 14); p.curve(12.5523, 14, 13, 14.4477, 13, 15); p.close();
            p.move(20, 15); p.curve(20, 15.5523, 19.5523, 16, 19, 16); p.curve(18.4477, 16, 18, 15.5523, 18, 15);
            p.curve(18, 14.4477, 18.4477, 14, 19, 14); p.curve(19.5523, 14, 20, 14.4477, 20, 15); p.close();
            p.move(6, 15); p.curve(6, 15.5523, 5.5523, 16, 5, 16); p.curve(4.4477, 16, 4, 15.5523, 4, 15);
            p.curve(4, 14.4477, 4.4477, 14, 5, 14); p.curve(5.5523, 14, 6, 14.4477, 6, 15); p.close();
        case .hand:
            p.move(18, 11); p.line(18, 6); p.curve(18, 4.8954, 17.1046, 4, 16, 4);
            p.curve(14.8954, 4, 14, 4.8954, 14, 6);
            p.move(14, 10); p.line(14, 4); p.curve(14, 2.8954, 13.1046, 2, 12, 2);
            p.curve(10.8954, 2, 10, 2.8954, 10, 4); p.line(10, 6);
            p.move(10, 10.5); p.line(10, 6); p.curve(10, 4.8954, 9.1046, 4, 8, 4); p.curve(6.8954, 4, 6, 4.8954, 6, 6);
            p.line(6, 14);
            p.move(18, 8); p.curve(18, 6.8954, 18.8954, 6, 20, 6); p.curve(21.1046, 6, 22, 6.8954, 22, 8);
            p.line(22, 14); p.curve(22, 18.4183, 18.4183, 22, 14, 22); p.line(12, 22);
            p.curve(9.2, 22, 7.5, 21.14, 6.01, 19.66); p.line(2.41, 16.06);
            p.curve(1.6954, 15.2686, 1.7274, 14.0556, 2.4827, 13.303);
            p.curve(3.2381, 12.5503, 4.4511, 12.5226, 5.24, 13.24); p.line(7, 15);
        case .hardDrive:
            p.move(22, 12); p.line(2, 12);
            p.move(5.45, 5.11); p.line(2, 12); p.line(2, 18); p.curve(2, 19.1046, 2.8954, 20, 4, 20); p.line(20, 20);
            p.curve(21.1046, 20, 22, 19.1046, 22, 18); p.line(22, 12); p.line(18.55, 5.11);
            p.curve(18.2123, 4.4303, 17.5189, 4.0004, 16.76, 4); p.line(7.24, 4);
            p.curve(6.4811, 4.0004, 5.7877, 4.4303, 5.45, 5.11); p.close();
            p.move(6, 16); p.line(6.01, 16);
            p.move(10, 16); p.line(10.01, 16);
        case .history:
            p.move(3, 12); p.curve(3, 16.9706, 7.0294, 21, 12, 21); p.curve(16.9706, 21, 21, 16.9706, 21, 12);
            p.curve(21, 7.0294, 16.9706, 3, 12, 3); p.curve(9.484, 3.0095, 7.069, 3.9912, 5.26, 5.74); p.line(3, 8);
            p.move(3, 3); p.line(3, 8); p.line(8, 8);
            p.move(12, 7); p.line(12, 12); p.line(16, 14);
        case .house:
            p.move(15, 21); p.line(15, 13); p.curve(15, 12.4477, 14.5523, 12, 14, 12); p.line(10, 12);
            p.curve(9.4477, 12, 9, 12.4477, 9, 13); p.line(9, 21);
            p.move(3, 10); p.curve(2.9999, 9.4111, 3.2592, 8.8521, 3.709, 8.472); p.line(10.709, 2.473);
            p.curve(11.4544, 1.843, 12.5456, 1.843, 13.291, 2.473); p.line(20.291, 8.472);
            p.curve(20.7408, 8.8521, 21.0001, 9.4111, 21, 10); p.line(21, 19);
            p.curve(21, 20.1046, 20.1046, 21, 19, 21); p.line(5, 21); p.curve(3.8954, 21, 3, 20.1046, 3, 19); p.close();
        case .info:
            p.move(22, 12); p.curve(22, 17.5228, 17.5228, 22, 12, 22); p.curve(6.4772, 22, 2, 17.5228, 2, 12);
            p.curve(2, 6.4772, 6.4772, 2, 12, 2); p.curve(17.5228, 2, 22, 6.4772, 22, 12); p.close();
            p.move(12, 16); p.line(12, 12);
            p.move(12, 8); p.line(12.01, 8);
        case .keyRound:
            p.move(2.586, 17.414); p.curve(2.2109, 17.789, 2.0001, 18.2976, 2, 18.828); p.line(2, 21);
            p.curve(2, 21.5523, 2.4477, 22, 3, 22); p.line(6, 22); p.curve(6.5523, 22, 7, 21.5523, 7, 21);
            p.line(7, 20); p.curve(7, 19.4477, 7.4477, 19, 8, 19); p.line(9, 19);
            p.curve(9.5523, 19, 10, 18.5523, 10, 18); p.line(10, 17); p.curve(10, 16.4477, 10.4477, 16, 11, 16);
            p.line(11.172, 16); p.curve(11.7024, 15.9999, 12.211, 15.7891, 12.586, 15.414); p.line(13.4, 14.6);
            p.curve(16.2622, 15.597, 19.4336, 14.4836, 21.0444, 11.9161);
            p.curve(22.6551, 9.3487, 22.2776, 6.0087, 20.1344, 3.8656);
            p.curve(17.9913, 1.7224, 14.6513, 1.3449, 12.0839, 2.9556);
            p.curve(9.5164, 4.5664, 8.403, 7.7378, 9.4, 10.6); p.close();
            p.move(17, 7.5); p.curve(17, 7.7761, 16.7761, 8, 16.5, 8); p.curve(16.2239, 8, 16, 7.7761, 16, 7.5);
            p.curve(16, 7.2239, 16.2239, 7, 16.5, 7); p.curve(16.7761, 7, 17, 7.2239, 17, 7.5); p.close();
            p.move(16.495, 7.5); p.line(16.505, 7.5);
        case .keyboard:
            p.move(10, 8); p.line(10.01, 8);
            p.move(12, 12); p.line(12.01, 12);
            p.move(14, 8); p.line(14.01, 8);
            p.move(16, 12); p.line(16.01, 12);
            p.move(18, 8); p.line(18.01, 8);
            p.move(6, 8); p.line(6.01, 8);
            p.move(7, 16); p.line(17, 16);
            p.move(8, 12); p.line(8.01, 12);
            p.move(4, 4); p.line(20, 4); p.curve(21.1046, 4, 22, 4.8954, 22, 6); p.line(22, 18);
            p.curve(22, 19.1046, 21.1046, 20, 20, 20); p.line(4, 20); p.curve(2.8954, 20, 2, 19.1046, 2, 18);
            p.line(2, 6); p.curve(2, 4.8954, 2.8954, 4, 4, 4); p.close();
        case .keyboardOff:
            p.move(20, 4); p.curve(21.1046, 4, 22, 4.8954, 22, 6);
            p.move(22, 6); p.line(22, 16.41);
            p.move(7, 16); p.line(16, 16);
            p.move(9.69, 4); p.line(20, 4);
            p.move(14, 8); p.line(14.01, 8);
            p.move(18, 8); p.line(18.01, 8);
            p.move(2, 2); p.line(22, 22);
            p.move(20, 20); p.line(4, 20); p.curve(2.8954, 20, 2, 19.1046, 2, 18); p.line(2, 6);
            p.curve(2, 4.8954, 2.8954, 4, 4, 4);
            p.move(6, 8); p.line(6.01, 8);
            p.move(8, 12); p.line(8.01, 12);
        case .layers:
            p.move(12.83, 2.18); p.curve(12.3028, 1.9395, 11.6972, 1.9395, 11.17, 2.18); p.line(2.6, 6.08);
            p.curve(2.2374, 6.2399, 2.0035, 6.5987, 2.0035, 6.995); p.curve(2.0035, 7.3913, 2.2374, 7.7501, 2.6, 7.91);
            p.line(11.18, 11.82); p.curve(11.7072, 12.0605, 12.3128, 12.0605, 12.84, 11.82); p.line(21.42, 7.92);
            p.curve(21.7826, 7.7601, 22.0165, 7.4013, 22.0165, 7.005);
            p.curve(22.0165, 6.6087, 21.7826, 6.2499, 21.42, 6.09); p.close();
            p.move(2, 12); p.curve(1.999, 12.3906, 2.2255, 12.746, 2.58, 12.91); p.line(11.18, 16.82);
            p.curve(11.7044, 17.0574, 12.3056, 17.0574, 12.83, 16.82); p.line(21.41, 12.92);
            p.curve(21.7717, 12.7574, 22.0031, 12.3965, 22, 12);
            p.move(2, 17); p.curve(1.999, 17.3906, 2.2255, 17.746, 2.58, 17.91); p.line(11.18, 21.82);
            p.curve(11.7044, 22.0574, 12.3056, 22.0574, 12.83, 21.82); p.line(21.41, 17.92);
            p.curve(21.7717, 17.7574, 22.0031, 17.3965, 22, 17);
        case .layoutPanelTop:
            p.move(4, 3); p.line(20, 3); p.curve(20.5523, 3, 21, 3.4477, 21, 4); p.line(21, 9);
            p.curve(21, 9.5523, 20.5523, 10, 20, 10); p.line(4, 10); p.curve(3.4477, 10, 3, 9.5523, 3, 9); p.line(3, 4);
            p.curve(3, 3.4477, 3.4477, 3, 4, 3); p.close();
            p.move(4, 14); p.line(9, 14); p.curve(9.5523, 14, 10, 14.4477, 10, 15); p.line(10, 20);
            p.curve(10, 20.5523, 9.5523, 21, 9, 21); p.line(4, 21); p.curve(3.4477, 21, 3, 20.5523, 3, 20);
            p.line(3, 15); p.curve(3, 14.4477, 3.4477, 14, 4, 14); p.close();
            p.move(15, 14); p.line(20, 14); p.curve(20.5523, 14, 21, 14.4477, 21, 15); p.line(21, 20);
            p.curve(21, 20.5523, 20.5523, 21, 20, 21); p.line(15, 21); p.curve(14.4477, 21, 14, 20.5523, 14, 20);
            p.line(14, 15); p.curve(14, 14.4477, 14.4477, 14, 15, 14); p.close();
        case .lightbulb:
            p.move(15, 14); p.curve(15.2, 13, 15.7, 12.3, 16.5, 11.5); p.curve(17.5, 10.6, 18, 9.3, 18, 8);
            p.curve(18, 4.6863, 15.3137, 2, 12, 2); p.curve(8.6863, 2, 6, 4.6863, 6, 8);
            p.curve(6, 9, 6.2, 10.2, 7.5, 11.5); p.curve(8.2, 12.2, 8.8, 13, 9, 14);
            p.move(9, 18); p.line(15, 18);
            p.move(10, 22); p.line(14, 22);
        case .lightbulbOff:
            p.move(16.8, 11.2); p.curve(17.6, 10.3, 18, 9.2, 18, 8);
            p.curve(17.996, 5.7953, 16.7831, 3.7704, 14.8412, 2.7263);
            p.curve(12.8993, 1.6823, 10.5413, 1.7874, 8.7, 3);
            p.move(2, 2); p.line(22, 22);
            p.move(6.3, 6.3); p.curve(5.5727, 8.1137, 6.0515, 10.1884, 7.5, 11.5); p.curve(8.2, 12.2, 8.8, 13, 9, 14);
            p.move(9, 18); p.line(15, 18);
            p.move(10, 22); p.line(14, 22);
        case .link:
            p.move(10, 13); p.curve(10.869, 14.1617, 12.1996, 14.8887, 13.6466, 14.9923);
            p.curve(15.0937, 15.096, 16.5144, 14.566, 17.54, 13.54); p.line(20.54, 10.54);
            p.curve(22.4349, 8.5781, 22.4078, 5.4596, 20.4791, 3.5309);
            p.curve(18.5504, 1.6022, 15.4319, 1.5751, 13.47, 3.47); p.line(11.75, 5.18);
            p.move(14, 11); p.curve(13.131, 9.8383, 11.8004, 9.1113, 10.3534, 9.0077);
            p.curve(8.9063, 8.904, 7.4856, 9.434, 6.46, 10.46); p.line(3.46, 13.46);
            p.curve(1.5651, 15.4219, 1.5922, 18.5404, 3.5209, 20.4691);
            p.curve(5.4496, 22.3978, 8.5681, 22.4249, 10.53, 20.53); p.line(12.24, 18.82);
        case .listRestart:
            p.move(21, 6); p.line(3, 6);
            p.move(7, 12); p.line(3, 12);
            p.move(7, 18); p.line(3, 18);
            p.move(12, 18); p.curve(13.2913, 19.7217, 15.5394, 20.424, 17.5811, 19.7434);
            p.curve(19.6228, 19.0628, 21, 17.1522, 21, 15); p.curve(21, 12.5147, 18.9853, 10.5, 16.5, 10.5);
            p.curve(15.17, 10.5, 13.96, 11.04, 13.09, 11.91); p.line(11, 14);
            p.move(11, 10); p.line(11, 14); p.line(15, 14);
        case .loaderCircle:
            p.move(21, 12); p.curve(20.9998, 15.899, 18.4891, 19.3544, 14.7809, 20.5592);
            p.curve(11.0727, 21.7639, 7.0105, 20.4439, 4.7188, 17.2895);
            p.curve(2.4271, 14.1351, 2.4271, 9.8638, 4.7188, 6.7095);
            p.curve(7.0106, 3.5552, 11.0728, 2.2352, 14.781, 3.44);
        case .lock:
            p.move(5, 11); p.line(19, 11); p.curve(20.1046, 11, 21, 11.8954, 21, 13); p.line(21, 20);
            p.curve(21, 21.1046, 20.1046, 22, 19, 22); p.line(5, 22); p.curve(3.8954, 22, 3, 21.1046, 3, 20);
            p.line(3, 13); p.curve(3, 11.8954, 3.8954, 11, 5, 11); p.close();
            p.move(7, 11); p.line(7, 7); p.curve(7, 4.2386, 9.2386, 2, 12, 2); p.curve(14.7614, 2, 17, 4.2386, 17, 7);
            p.line(17, 11);
        case .lockOpen:
            p.move(5, 11); p.line(19, 11); p.curve(20.1046, 11, 21, 11.8954, 21, 13); p.line(21, 20);
            p.curve(21, 21.1046, 20.1046, 22, 19, 22); p.line(5, 22); p.curve(3.8954, 22, 3, 21.1046, 3, 20);
            p.line(3, 13); p.curve(3, 11.8954, 3.8954, 11, 5, 11); p.close();
            p.move(7, 11); p.line(7, 7); p.curve(6.9974, 4.4312, 8.9417, 2.2784, 11.4975, 2.0203);
            p.curve(14.0533, 1.7621, 16.3888, 3.4826, 16.9, 6);
        case .logOut:
            p.move(9, 21); p.line(5, 21); p.curve(3.8954, 21, 3, 20.1046, 3, 19); p.line(3, 5);
            p.curve(3, 3.8954, 3.8954, 3, 5, 3); p.line(9, 3);
            p.move(16, 17); p.line(21, 12); p.line(16, 7);
            p.move(21, 12); p.line(9, 12);
        case .maximize2:
            p.move(15, 3); p.line(21, 3); p.line(21, 9);
            p.move(9, 21); p.line(3, 21); p.line(3, 15);
            p.move(21, 3); p.line(14, 10);
            p.move(3, 21); p.line(10, 14);
        case .mic:
            p.move(12, 2); p.curve(10.3431, 2, 9, 3.3431, 9, 5); p.line(9, 12);
            p.curve(9, 13.6569, 10.3431, 15, 12, 15); p.curve(13.6569, 15, 15, 13.6569, 15, 12); p.line(15, 5);
            p.curve(15, 3.3431, 13.6569, 2, 12, 2); p.close();
            p.move(19, 10); p.line(19, 12); p.curve(19, 15.866, 15.866, 19, 12, 19);
            p.curve(8.134, 19, 5, 15.866, 5, 12); p.line(5, 10);
            p.move(12, 19); p.line(12, 22);
        case .micOff:
            p.move(2, 2); p.line(22, 22);
            p.move(18.89, 13.23); p.curve(18.9622, 12.824, 18.999, 12.4124, 19, 12); p.line(19, 10);
            p.move(5, 10); p.line(5, 12); p.curve(4.9584, 14.8627, 6.6642, 17.4622, 9.307, 18.5633);
            p.curve(11.9497, 19.6645, 14.9966, 19.0453, 17, 17);
            p.move(15, 9.34); p.line(15, 5); p.curve(14.9916, 3.6134, 14.0341, 2.4132, 12.684, 2.0971);
            p.curve(11.3339, 1.781, 9.9431, 2.4313, 9.32, 3.67);
            p.move(9, 9); p.line(9, 12); p.curve(9.0011, 13.2126, 9.732, 14.3053, 10.8523, 14.7691);
            p.curve(11.9726, 15.233, 13.2621, 14.9769, 14.12, 14.12);
            p.move(12, 19); p.line(12, 22);
        case .minimize2:
            p.move(4, 14); p.line(10, 14); p.line(10, 20);
            p.move(20, 10); p.line(14, 10); p.line(14, 4);
            p.move(14, 10); p.line(21, 3);
            p.move(3, 21); p.line(10, 14);
        case .minus:
            p.move(5, 12); p.line(19, 12);
        case .monitor:
            p.move(4, 3); p.line(20, 3); p.curve(21.1046, 3, 22, 3.8954, 22, 5); p.line(22, 15);
            p.curve(22, 16.1046, 21.1046, 17, 20, 17); p.line(4, 17); p.curve(2.8954, 17, 2, 16.1046, 2, 15);
            p.line(2, 5); p.curve(2, 3.8954, 2.8954, 3, 4, 3); p.close();
            p.move(8, 21); p.line(16, 21);
            p.move(12, 17); p.line(12, 21);
        case .monitorSmartphone:
            p.move(18, 8); p.line(18, 6); p.curve(18, 4.8954, 17.1046, 4, 16, 4); p.line(4, 4);
            p.curve(2.8954, 4, 2, 4.8954, 2, 6); p.line(2, 13); p.curve(2, 14.1046, 2.8954, 15, 4, 15); p.line(12, 15);
            p.move(10, 19); p.line(10, 15.04); p.line(10, 18.19);
            p.move(7, 19); p.line(12, 19);
            p.move(18, 12); p.line(20, 12); p.curve(21.1046, 12, 22, 12.8954, 22, 14); p.line(22, 20);
            p.curve(22, 21.1046, 21.1046, 22, 20, 22); p.line(18, 22); p.curve(16.8954, 22, 16, 21.1046, 16, 20);
            p.line(16, 14); p.curve(16, 12.8954, 16.8954, 12, 18, 12); p.close();
        case .moon:
            p.move(12, 3); p.curve(9.5147, 5.4853, 9.5147, 9.5147, 12, 12);
            p.curve(14.4853, 14.4853, 18.5147, 14.4853, 21, 12); p.curve(21, 16.9706, 16.9706, 21, 12, 21);
            p.curve(7.0294, 21, 3, 16.9706, 3, 12); p.curve(3, 7.0294, 7.0294, 3, 12, 3); p.close();
        case .mousePointer2:
            p.move(4.037, 4.688); p.curve(3.9562, 4.5016, 3.9975, 4.2848, 4.1412, 4.1412);
            p.curve(4.2848, 3.9975, 4.5016, 3.9562, 4.688, 4.037); p.line(20.688, 10.537);
            p.curve(20.8875, 10.6183, 21.0125, 10.8183, 20.9982, 11.0332);
            p.curve(20.9839, 11.2482, 20.8335, 11.4299, 20.625, 11.484); p.line(14.501, 13.064);
            p.curve(13.7963, 13.2452, 13.2456, 13.7947, 13.063, 14.499); p.line(11.484, 20.625);
            p.curve(11.4299, 20.8335, 11.2482, 20.9839, 11.0332, 20.9982);
            p.curve(10.8183, 21.0125, 10.6183, 20.8875, 10.537, 20.688); p.close();
        case .mousePointerClick:
            p.move(14, 4.1); p.line(12, 6);
            p.move(5.1, 8); p.line(2.2, 7.2);
            p.move(6, 12); p.line(4.1, 14);
            p.move(7.2, 2.2); p.line(8, 5.1);
            p.move(9.037, 9.69); p.curve(8.9577, 9.5031, 8.9997, 9.2868, 9.1433, 9.1433);
            p.curve(9.2868, 8.9997, 9.5031, 8.9577, 9.69, 9.037); p.line(20.69, 13.537);
            p.curve(20.8909, 13.6194, 21.0156, 13.822, 20.9987, 14.0385);
            p.curve(20.9818, 14.2549, 20.8272, 14.4357, 20.616, 14.486); p.line(16.267, 15.527);
            p.curve(15.9009, 15.6144, 15.6149, 15.9, 15.527, 16.266); p.line(14.487, 20.616);
            p.curve(14.4373, 20.828, 14.2561, 20.9834, 14.0391, 21.0003);
            p.curve(13.822, 21.0172, 13.619, 20.8917, 13.537, 20.69); p.close();
        case .move:
            p.move(12, 2); p.line(12, 22);
            p.move(15, 19); p.line(12, 22); p.line(9, 19);
            p.move(19, 9); p.line(22, 12); p.line(19, 15);
            p.move(2, 12); p.line(22, 12);
            p.move(5, 9); p.line(2, 12); p.line(5, 15);
            p.move(9, 5); p.line(12, 2); p.line(15, 5);
        case .network:
            p.move(17, 16); p.line(21, 16); p.curve(21.5523, 16, 22, 16.4477, 22, 17); p.line(22, 21);
            p.curve(22, 21.5523, 21.5523, 22, 21, 22); p.line(17, 22); p.curve(16.4477, 22, 16, 21.5523, 16, 21);
            p.line(16, 17); p.curve(16, 16.4477, 16.4477, 16, 17, 16); p.close();
            p.move(3, 16); p.line(7, 16); p.curve(7.5523, 16, 8, 16.4477, 8, 17); p.line(8, 21);
            p.curve(8, 21.5523, 7.5523, 22, 7, 22); p.line(3, 22); p.curve(2.4477, 22, 2, 21.5523, 2, 21);
            p.line(2, 17); p.curve(2, 16.4477, 2.4477, 16, 3, 16); p.close();
            p.move(10, 2); p.line(14, 2); p.curve(14.5523, 2, 15, 2.4477, 15, 3); p.line(15, 7);
            p.curve(15, 7.5523, 14.5523, 8, 14, 8); p.line(10, 8); p.curve(9.4477, 8, 9, 7.5523, 9, 7); p.line(9, 3);
            p.curve(9, 2.4477, 9.4477, 2, 10, 2); p.close();
            p.move(5, 16); p.line(5, 13); p.curve(5, 12.4477, 5.4477, 12, 6, 12); p.line(18, 12);
            p.curve(18.5523, 12, 19, 12.4477, 19, 13); p.line(19, 16);
            p.move(12, 12); p.line(12, 8);
        case .octagonX:
            p.move(15, 9); p.line(9, 15);
            p.move(2.586, 16.726); p.curve(2.2109, 16.351, 2.0001, 15.8424, 2, 15.312); p.line(2, 8.688);
            p.curve(2.0001, 8.1576, 2.2109, 7.649, 2.586, 7.274); p.line(7.274, 2.586);
            p.curve(7.649, 2.2109, 8.1576, 2.0001, 8.688, 2); p.line(15.312, 2);
            p.curve(15.8424, 2.0001, 16.351, 2.2109, 16.726, 2.586); p.line(21.414, 7.274);
            p.curve(21.7891, 7.649, 21.9999, 8.1576, 22, 8.688); p.line(22, 15.312);
            p.curve(21.9999, 15.8424, 21.7891, 16.351, 21.414, 16.726); p.line(16.726, 21.414);
            p.curve(16.351, 21.7891, 15.8424, 21.9999, 15.312, 22); p.line(8.688, 22);
            p.curve(8.1576, 21.9999, 7.649, 21.7891, 7.274, 21.414); p.close();
            p.move(9, 9); p.line(15, 15);
        case .option:
            p.move(3, 3); p.line(9, 3); p.line(15, 21); p.line(21, 21);
            p.move(14, 3); p.line(21, 3);
        case .palette:
            p.move(14, 6.5); p.curve(14, 6.7761, 13.7761, 7, 13.5, 7); p.curve(13.2239, 7, 13, 6.7761, 13, 6.5);
            p.curve(13, 6.2239, 13.2239, 6, 13.5, 6); p.curve(13.7761, 6, 14, 6.2239, 14, 6.5); p.close();
            p.move(13.495, 6.5); p.line(13.505, 6.5);
            p.move(18, 10.5); p.curve(18, 10.7761, 17.7761, 11, 17.5, 11); p.curve(17.2239, 11, 17, 10.7761, 17, 10.5);
            p.curve(17, 10.2239, 17.2239, 10, 17.5, 10); p.curve(17.7761, 10, 18, 10.2239, 18, 10.5); p.close();
            p.move(17.495, 10.5); p.line(17.505, 10.5);
            p.move(9, 7.5); p.curve(9, 7.7761, 8.7761, 8, 8.5, 8); p.curve(8.2239, 8, 8, 7.7761, 8, 7.5);
            p.curve(8, 7.2239, 8.2239, 7, 8.5, 7); p.curve(8.7761, 7, 9, 7.2239, 9, 7.5); p.close(); p.move(8.495, 7.5);
            p.line(8.505, 7.5);
            p.move(7, 12.5); p.curve(7, 12.7761, 6.7761, 13, 6.5, 13); p.curve(6.2239, 13, 6, 12.7761, 6, 12.5);
            p.curve(6, 12.2239, 6.2239, 12, 6.5, 12); p.curve(6.7761, 12, 7, 12.2239, 7, 12.5); p.close();
            p.move(6.495, 12.5); p.line(6.505, 12.5);
            p.move(12, 2); p.curve(6.5, 2, 2, 6.5, 2, 12); p.curve(2, 17.5, 6.5, 22, 12, 22);
            p.curve(12.926, 22, 13.648, 21.254, 13.648, 20.312);
            p.curve(13.648, 19.875, 13.468, 19.477, 13.211, 19.187);
            p.curve(12.921, 18.898, 12.773, 18.535, 12.773, 18.062);
            p.curve(12.7653, 17.6173, 12.9386, 17.1886, 13.2531, 16.8741);
            p.curve(13.5676, 16.5596, 13.9963, 16.3863, 14.441, 16.394); p.line(16.437, 16.394);
            p.curve(19.488, 16.394, 21.992, 13.891, 21.992, 10.84); p.curve(21.965, 6.012, 17.461, 2, 12, 2); p.close();
        case .panelBottom:
            p.move(5, 3); p.line(19, 3); p.curve(20.1046, 3, 21, 3.8954, 21, 5); p.line(21, 19);
            p.curve(21, 20.1046, 20.1046, 21, 19, 21); p.line(5, 21); p.curve(3.8954, 21, 3, 20.1046, 3, 19);
            p.line(3, 5); p.curve(3, 3.8954, 3.8954, 3, 5, 3); p.close();
            p.move(3, 15); p.line(21, 15);
        case .panelTop:
            p.move(5, 3); p.line(19, 3); p.curve(20.1046, 3, 21, 3.8954, 21, 5); p.line(21, 19);
            p.curve(21, 20.1046, 20.1046, 21, 19, 21); p.line(5, 21); p.curve(3.8954, 21, 3, 20.1046, 3, 19);
            p.line(3, 5); p.curve(3, 3.8954, 3.8954, 3, 5, 3); p.close();
            p.move(3, 9); p.line(21, 9);
        case .pencil:
            p.move(21.174, 6.812); p.curve(22.275, 5.7113, 22.2752, 3.9265, 21.1745, 2.8255);
            p.curve(20.0738, 1.7245, 18.289, 1.7243, 17.188, 2.825); p.line(3.842, 16.174);
            p.curve(3.6098, 16.4055, 3.4381, 16.6905, 3.342, 17.004); p.line(2.021, 21.356);
            p.curve(1.9683, 21.5322, 2.0167, 21.7231, 2.1468, 21.853);
            p.curve(2.2769, 21.9829, 2.4679, 22.0309, 2.644, 21.978); p.line(6.997, 20.658);
            p.curve(7.3102, 20.5628, 7.5952, 20.3921, 7.827, 20.161); p.close();
            p.move(15, 5); p.line(19, 9);
        case .plugZap:
            p.move(6.3, 20.3); p.curve(6.7503, 20.7519, 7.362, 21.0059, 8, 21.0059);
            p.curve(8.638, 21.0059, 9.2497, 20.7519, 9.7, 20.3); p.line(12, 18); p.line(6, 12); p.line(3.7, 14.3);
            p.curve(3.2481, 14.7503, 2.9941, 15.362, 2.9941, 16); p.curve(2.9941, 16.638, 3.2481, 17.2497, 3.7, 17.7);
            p.close();
            p.move(2, 22); p.line(5, 19);
            p.move(7.5, 13.5); p.line(10, 11);
            p.move(10.5, 16.5); p.line(13, 14);
            p.move(18, 3); p.line(14, 7); p.line(20, 7); p.line(16, 11);
        case .plus:
            p.move(5, 12); p.line(19, 12);
            p.move(12, 5); p.line(12, 19);
        case .pointer:
            p.move(22, 14); p.curve(22, 18.4183, 18.4183, 22, 14, 22);
            p.move(18, 11); p.line(18, 10); p.curve(18, 8.8954, 17.1046, 8, 16, 8);
            p.curve(14.8954, 8, 14, 8.8954, 14, 10);
            p.move(14, 10); p.line(14, 9); p.curve(14, 7.8954, 13.1046, 7, 12, 7);
            p.curve(10.8954, 7, 10, 7.8954, 10, 9); p.line(10, 10);
            p.move(10, 9.5); p.line(10, 4); p.curve(10, 2.8954, 9.1046, 2, 8, 2); p.curve(6.8954, 2, 6, 2.8954, 6, 4);
            p.line(6, 14);
            p.move(18, 11); p.curve(18, 9.8954, 18.8954, 9, 20, 9); p.curve(21.1046, 9, 22, 9.8954, 22, 11);
            p.line(22, 14); p.curve(22, 18.4183, 18.4183, 22, 14, 22); p.line(12, 22);
            p.curve(9.2, 22, 7.5, 21.14, 6.01, 19.66); p.line(2.41, 16.06);
            p.curve(1.6954, 15.2686, 1.7274, 14.0556, 2.4827, 13.303);
            p.curve(3.2381, 12.5503, 4.4511, 12.5226, 5.24, 13.24); p.line(7, 15);
        case .power:
            p.move(12, 2); p.line(12, 12);
            p.move(18.4, 6.6); p.curve(21.9086, 10.1099, 21.9138, 15.7975, 18.4117, 19.3138);
            p.curve(14.9096, 22.8302, 9.222, 22.848, 5.6979, 19.3537);
            p.curve(2.1739, 15.8593, 2.1435, 10.1718, 5.63, 6.64);
        case .qrCode:
            p.move(4, 3); p.line(7, 3); p.curve(7.5523, 3, 8, 3.4477, 8, 4); p.line(8, 7);
            p.curve(8, 7.5523, 7.5523, 8, 7, 8); p.line(4, 8); p.curve(3.4477, 8, 3, 7.5523, 3, 7); p.line(3, 4);
            p.curve(3, 3.4477, 3.4477, 3, 4, 3); p.close();
            p.move(17, 3); p.line(20, 3); p.curve(20.5523, 3, 21, 3.4477, 21, 4); p.line(21, 7);
            p.curve(21, 7.5523, 20.5523, 8, 20, 8); p.line(17, 8); p.curve(16.4477, 8, 16, 7.5523, 16, 7);
            p.line(16, 4); p.curve(16, 3.4477, 16.4477, 3, 17, 3); p.close();
            p.move(4, 16); p.line(7, 16); p.curve(7.5523, 16, 8, 16.4477, 8, 17); p.line(8, 20);
            p.curve(8, 20.5523, 7.5523, 21, 7, 21); p.line(4, 21); p.curve(3.4477, 21, 3, 20.5523, 3, 20);
            p.line(3, 17); p.curve(3, 16.4477, 3.4477, 16, 4, 16); p.close();
            p.move(21, 16); p.line(18, 16); p.curve(16.8954, 16, 16, 16.8954, 16, 18); p.line(16, 21);
            p.move(21, 21); p.line(21, 21.01);
            p.move(12, 7); p.line(12, 10); p.curve(12, 11.1046, 11.1046, 12, 10, 12); p.line(7, 12);
            p.move(3, 12); p.line(3.01, 12);
            p.move(12, 3); p.line(12.01, 3);
            p.move(12, 16); p.line(12, 16.01);
            p.move(16, 12); p.line(17, 12);
            p.move(21, 12); p.line(21, 12.01);
            p.move(12, 21); p.line(12, 20);
        case .radar:
            p.move(19.07, 4.93); p.curve(15.8683, 1.7249, 10.912, 1.0725, 6.99, 3.34);
            p.move(4, 6); p.line(4.01, 6);
            p.move(2.29, 9.62); p.curve(1.261, 13.8112, 3.0369, 18.1898, 6.6948, 20.48);
            p.curve(10.3527, 22.7703, 15.0672, 22.4555, 18.3881, 19.6992);
            p.curve(21.709, 16.943, 22.8871, 12.3672, 21.31, 8.35);
            p.move(16.24, 7.76); p.curve(14.672, 6.1829, 12.3604, 5.6025, 10.2334, 6.2517);
            p.curve(8.1064, 6.901, 6.513, 8.6734, 6.093, 10.8573);
            p.curve(5.6731, 13.0412, 6.4955, 15.2782, 8.23, 16.67);
            p.move(12, 18); p.line(12.01, 18);
            p.move(17.99, 11.66); p.curve(18.1004, 13.5901, 17.2739, 15.4552, 15.77, 16.67);
            p.move(14, 12); p.curve(14, 13.1046, 13.1046, 14, 12, 14); p.curve(10.8954, 14, 10, 13.1046, 10, 12);
            p.curve(10, 10.8954, 10.8954, 10, 12, 10); p.curve(13.1046, 10, 14, 10.8954, 14, 12); p.close();
            p.move(13.41, 10.59); p.line(19.07, 4.93);
        case .radioTower:
            p.move(4.9, 16.1); p.curve(1, 12.2, 1, 5.8, 4.9, 1.9);
            p.move(7.8, 4.7); p.curve(5.8483, 6.7223, 5.5187, 9.8115, 7, 12.2);
            p.move(14, 9); p.curve(14, 10.1046, 13.1046, 11, 12, 11); p.curve(10.8954, 11, 10, 10.1046, 10, 9);
            p.curve(10, 7.8954, 10.8954, 7, 12, 7); p.curve(13.1046, 7, 14, 7.8954, 14, 9); p.close();
            p.move(16.2, 4.8); p.curve(18.2, 6.8, 18.46, 9.91, 17, 12.27);
            p.move(19.1, 1.9); p.curve(20.9723, 3.7684, 22.0244, 6.3049, 22.0244, 8.95);
            p.curve(22.0244, 11.5951, 20.9723, 14.1316, 19.1, 16);
            p.move(9.5, 18); p.line(14.5, 18);
            p.move(8, 22); p.line(12, 11); p.line(16, 22);
        case .rectangleHorizontal:
            p.move(4, 6); p.line(20, 6); p.curve(21.1046, 6, 22, 6.8954, 22, 8); p.line(22, 16);
            p.curve(22, 17.1046, 21.1046, 18, 20, 18); p.line(4, 18); p.curve(2.8954, 18, 2, 17.1046, 2, 16);
            p.line(2, 8); p.curve(2, 6.8954, 2.8954, 6, 4, 6); p.close();
        case .refreshCw:
            p.move(3, 12); p.curve(3, 7.0294, 7.0294, 3, 12, 3); p.curve(14.516, 3.0095, 16.931, 3.9912, 18.74, 5.74);
            p.line(21, 8);
            p.move(21, 3); p.line(21, 8); p.line(16, 8);
            p.move(21, 12); p.curve(21, 16.9706, 16.9706, 21, 12, 21);
            p.curve(9.484, 20.9905, 7.069, 20.0088, 5.26, 18.26); p.line(3, 16);
            p.move(8, 16); p.line(3, 16); p.line(3, 21);
        case .`repeat`:
            p.move(17, 2); p.line(21, 6); p.line(17, 10);
            p.move(3, 11); p.line(3, 10); p.curve(3, 7.7909, 4.7909, 6, 7, 6); p.line(21, 6);
            p.move(7, 22); p.line(3, 18); p.line(7, 14);
            p.move(21, 13); p.line(21, 14); p.curve(21, 16.2091, 19.2091, 18, 17, 18); p.line(3, 18);
        case .rotateCcw:
            p.move(3, 12); p.curve(3, 16.9706, 7.0294, 21, 12, 21); p.curve(16.9706, 21, 21, 16.9706, 21, 12);
            p.curve(21, 7.0294, 16.9706, 3, 12, 3); p.curve(9.484, 3.0095, 7.069, 3.9912, 5.26, 5.74); p.line(3, 8);
            p.move(3, 3); p.line(3, 8); p.line(8, 8);
        case .rotateCw:
            p.move(21, 12); p.curve(21, 16.9706, 16.9706, 21, 12, 21); p.curve(7.0294, 21, 3, 16.9706, 3, 12);
            p.curve(3, 7.0294, 7.0294, 3, 12, 3); p.curve(14.52, 3, 16.93, 4, 18.74, 5.74); p.line(21, 8);
            p.move(21, 3); p.line(21, 8); p.line(16, 8);
        case .router:
            p.move(4, 14); p.line(20, 14); p.curve(21.1046, 14, 22, 14.8954, 22, 16); p.line(22, 20);
            p.curve(22, 21.1046, 21.1046, 22, 20, 22); p.line(4, 22); p.curve(2.8954, 22, 2, 21.1046, 2, 20);
            p.line(2, 16); p.curve(2, 14.8954, 2.8954, 14, 4, 14); p.close();
            p.move(6.01, 18); p.line(6, 18);
            p.move(10.01, 18); p.line(10, 18);
            p.move(15, 10); p.line(15, 14);
            p.move(17.84, 7.17); p.curve(17.0897, 6.4189, 16.0716, 5.9969, 15.01, 5.9969);
            p.curve(13.9484, 5.9969, 12.9303, 6.4189, 12.18, 7.17);
            p.move(20.66, 4.34); p.curve(17.5362, 1.2183, 12.4738, 1.2183, 9.35, 4.34);
        case .satelliteDish:
            p.move(4, 10); p.curve(2.3228, 12.869, 2.7919, 16.5083, 5.1418, 18.8582);
            p.curve(7.4917, 21.2081, 11.131, 21.6772, 14, 20); p.close();
            p.move(9, 15); p.line(12, 12);
            p.move(17, 13); p.curve(17, 9.6863, 14.3137, 7, 11, 7);
            p.move(21, 13); p.curve(21, 7.4772, 16.5228, 3, 11, 3);
        case .save:
            p.move(15.2, 3); p.curve(15.7275, 3.0075, 16.2307, 3.2232, 16.6, 3.6); p.line(20.4, 7.4);
            p.curve(20.7768, 7.7693, 20.9925, 8.2725, 21, 8.8); p.line(21, 19);
            p.curve(21, 20.1046, 20.1046, 21, 19, 21); p.line(5, 21); p.curve(3.8954, 21, 3, 20.1046, 3, 19);
            p.line(3, 5); p.curve(3, 3.8954, 3.8954, 3, 5, 3); p.close();
            p.move(17, 21); p.line(17, 14); p.curve(17, 13.4477, 16.5523, 13, 16, 13); p.line(8, 13);
            p.curve(7.4477, 13, 7, 13.4477, 7, 14); p.line(7, 21);
            p.move(7, 3); p.line(7, 7); p.curve(7, 7.5523, 7.4477, 8, 8, 8); p.line(15, 8);
        case .scan:
            p.move(3, 7); p.line(3, 5); p.curve(3, 3.8954, 3.8954, 3, 5, 3); p.line(7, 3);
            p.move(17, 3); p.line(19, 3); p.curve(20.1046, 3, 21, 3.8954, 21, 5); p.line(21, 7);
            p.move(21, 17); p.line(21, 19); p.curve(21, 20.1046, 20.1046, 21, 19, 21); p.line(17, 21);
            p.move(7, 21); p.line(5, 21); p.curve(3.8954, 21, 3, 20.1046, 3, 19); p.line(3, 17);
        case .scanEye:
            p.move(3, 7); p.line(3, 5); p.curve(3, 3.8954, 3.8954, 3, 5, 3); p.line(7, 3);
            p.move(17, 3); p.line(19, 3); p.curve(20.1046, 3, 21, 3.8954, 21, 5); p.line(21, 7);
            p.move(21, 17); p.line(21, 19); p.curve(21, 20.1046, 20.1046, 21, 19, 21); p.line(17, 21);
            p.move(7, 21); p.line(5, 21); p.curve(3.8954, 21, 3, 20.1046, 3, 19); p.line(3, 17);
            p.move(13, 12); p.curve(13, 12.5523, 12.5523, 13, 12, 13); p.curve(11.4477, 13, 11, 12.5523, 11, 12);
            p.curve(11, 11.4477, 11.4477, 11, 12, 11); p.curve(12.5523, 11, 13, 11.4477, 13, 12); p.close();
            p.move(18.944, 12.33); p.curve(19.0187, 12.1163, 19.0187, 11.8837, 18.944, 11.67);
            p.curve(17.7924, 8.8482, 15.0477, 7.0039, 12, 7.0039);
            p.curve(8.9523, 7.0039, 6.2076, 8.8482, 5.056, 11.67);
            p.curve(4.9813, 11.8837, 4.9813, 12.1163, 5.056, 12.33);
            p.curve(6.2076, 15.1518, 8.9523, 16.9961, 12, 16.9961);
            p.curve(15.0477, 16.9961, 17.7924, 15.1518, 18.944, 12.33);
        case .scanLine:
            p.move(3, 7); p.line(3, 5); p.curve(3, 3.8954, 3.8954, 3, 5, 3); p.line(7, 3);
            p.move(17, 3); p.line(19, 3); p.curve(20.1046, 3, 21, 3.8954, 21, 5); p.line(21, 7);
            p.move(21, 17); p.line(21, 19); p.curve(21, 20.1046, 20.1046, 21, 19, 21); p.line(17, 21);
            p.move(7, 21); p.line(5, 21); p.curve(3.8954, 21, 3, 20.1046, 3, 19); p.line(3, 17);
            p.move(7, 12); p.line(17, 12);
        case .scanQrCode:
            p.move(17, 12); p.line(17, 16); p.curve(17, 16.5523, 16.5523, 17, 16, 17); p.line(12, 17);
            p.move(17, 3); p.line(19, 3); p.curve(20.1046, 3, 21, 3.8954, 21, 5); p.line(21, 7);
            p.move(17, 8); p.line(17, 7);
            p.move(21, 17); p.line(21, 19); p.curve(21, 20.1046, 20.1046, 21, 19, 21); p.line(17, 21);
            p.move(3, 7); p.line(3, 5); p.curve(3, 3.8954, 3.8954, 3, 5, 3); p.line(7, 3);
            p.move(7, 17); p.line(7.01, 17);
            p.move(7, 21); p.line(5, 21); p.curve(3.8954, 21, 3, 20.1046, 3, 19); p.line(3, 17);
            p.move(8, 7); p.line(11, 7); p.curve(11.5523, 7, 12, 7.4477, 12, 8); p.line(12, 11);
            p.curve(12, 11.5523, 11.5523, 12, 11, 12); p.line(8, 12); p.curve(7.4477, 12, 7, 11.5523, 7, 11);
            p.line(7, 8); p.curve(7, 7.4477, 7.4477, 7, 8, 7); p.close();
        case .scanText:
            p.move(3, 7); p.line(3, 5); p.curve(3, 3.8954, 3.8954, 3, 5, 3); p.line(7, 3);
            p.move(17, 3); p.line(19, 3); p.curve(20.1046, 3, 21, 3.8954, 21, 5); p.line(21, 7);
            p.move(21, 17); p.line(21, 19); p.curve(21, 20.1046, 20.1046, 21, 19, 21); p.line(17, 21);
            p.move(7, 21); p.line(5, 21); p.curve(3.8954, 21, 3, 20.1046, 3, 19); p.line(3, 17);
            p.move(7, 8); p.line(15, 8);
            p.move(7, 12); p.line(17, 12);
            p.move(7, 16); p.line(13, 16);
        case .screenShare:
            p.move(13, 3); p.line(4, 3); p.curve(2.8954, 3, 2, 3.8954, 2, 5); p.line(2, 15);
            p.curve(2, 16.1046, 2.8954, 17, 4, 17); p.line(20, 17); p.curve(21.1046, 17, 22, 16.1046, 22, 15);
            p.line(22, 12);
            p.move(8, 21); p.line(16, 21);
            p.move(12, 17); p.line(12, 21);
            p.move(17, 8); p.line(22, 3);
            p.move(17, 3); p.line(22, 3); p.line(22, 8);
        case .search:
            p.move(19, 11); p.curve(19, 15.4183, 15.4183, 19, 11, 19); p.curve(6.5817, 19, 3, 15.4183, 3, 11);
            p.curve(3, 6.5817, 6.5817, 3, 11, 3); p.curve(15.4183, 3, 19, 6.5817, 19, 11); p.close();
            p.move(21, 21); p.line(16.7, 16.7);
        case .server:
            p.move(4, 2); p.line(20, 2); p.curve(21.1046, 2, 22, 2.8954, 22, 4); p.line(22, 8);
            p.curve(22, 9.1046, 21.1046, 10, 20, 10); p.line(4, 10); p.curve(2.8954, 10, 2, 9.1046, 2, 8); p.line(2, 4);
            p.curve(2, 2.8954, 2.8954, 2, 4, 2); p.close();
            p.move(4, 14); p.line(20, 14); p.curve(21.1046, 14, 22, 14.8954, 22, 16); p.line(22, 20);
            p.curve(22, 21.1046, 21.1046, 22, 20, 22); p.line(4, 22); p.curve(2.8954, 22, 2, 21.1046, 2, 20);
            p.line(2, 16); p.curve(2, 14.8954, 2.8954, 14, 4, 14); p.close();
            p.move(6, 6); p.line(6.01, 6);
            p.move(6, 18); p.line(6.01, 18);
        case .settings:
            p.move(12.22, 2); p.line(11.78, 2); p.curve(10.6754, 2, 9.78, 2.8954, 9.78, 4); p.line(9.78, 4.18);
            p.curve(9.7793, 4.8938, 9.3982, 5.5531, 8.78, 5.91); p.line(8.35, 6.16);
            p.curve(7.7312, 6.5173, 6.9688, 6.5173, 6.35, 6.16); p.line(6.2, 6.08);
            p.curve(5.2444, 5.5288, 4.0229, 5.8554, 3.47, 6.81); p.line(3.25, 7.19);
            p.curve(2.6988, 8.1456, 3.0254, 9.3671, 3.98, 9.92); p.line(4.13, 10.02);
            p.curve(4.7451, 10.3751, 5.1257, 11.0298, 5.13, 11.74); p.line(5.13, 12.25);
            p.curve(5.1328, 12.9674, 4.7513, 13.6313, 4.13, 13.99); p.line(3.98, 14.08);
            p.curve(3.0254, 14.6329, 2.6988, 15.8544, 3.25, 16.81); p.line(3.47, 17.19);
            p.curve(4.0229, 18.1446, 5.2444, 18.4712, 6.2, 17.92); p.line(6.35, 17.84);
            p.curve(6.9688, 17.4827, 7.7312, 17.4827, 8.35, 17.84); p.line(8.78, 18.09);
            p.curve(9.3982, 18.4469, 9.7793, 19.1062, 9.78, 19.82); p.line(9.78, 20);
            p.curve(9.78, 21.1046, 10.6754, 22, 11.78, 22); p.line(12.22, 22);
            p.curve(13.3246, 22, 14.22, 21.1046, 14.22, 20); p.line(14.22, 19.82);
            p.curve(14.2207, 19.1062, 14.6018, 18.4469, 15.22, 18.09); p.line(15.65, 17.84);
            p.curve(16.2688, 17.4827, 17.0312, 17.4827, 17.65, 17.84); p.line(17.8, 17.92);
            p.curve(18.7556, 18.4712, 19.9771, 18.1446, 20.53, 17.19); p.line(20.75, 16.8);
            p.curve(21.3012, 15.8444, 20.9746, 14.6229, 20.02, 14.07); p.line(19.87, 13.99);
            p.curve(19.2487, 13.6313, 18.8672, 12.9674, 18.87, 12.25); p.line(18.87, 11.75);
            p.curve(18.8672, 11.0326, 19.2487, 10.3687, 19.87, 10.01); p.line(20.02, 9.92);
            p.curve(20.9746, 9.3671, 21.3012, 8.1456, 20.75, 7.19); p.line(20.53, 6.81);
            p.curve(19.9771, 5.8554, 18.7556, 5.5288, 17.8, 6.08); p.line(17.65, 6.16);
            p.curve(17.0312, 6.5173, 16.2688, 6.5173, 15.65, 6.16); p.line(15.22, 5.91);
            p.curve(14.6018, 5.5531, 14.2207, 4.8938, 14.22, 4.18); p.line(14.22, 4);
            p.curve(14.22, 2.8954, 13.3246, 2, 12.22, 2); p.close();
            p.move(15, 12); p.curve(15, 13.6569, 13.6569, 15, 12, 15); p.curve(10.3431, 15, 9, 13.6569, 9, 12);
            p.curve(9, 10.3431, 10.3431, 9, 12, 9); p.curve(13.6569, 9, 15, 10.3431, 15, 12); p.close();
        case .shieldAlert:
            p.move(20, 13); p.curve(20, 18, 16.5, 20.5, 12.34, 21.95);
            p.curve(12.1222, 22.0238, 11.8855, 22.0203, 11.67, 21.94); p.curve(7.5, 20.5, 4, 18, 4, 13); p.line(4, 6);
            p.curve(4, 5.4477, 4.4477, 5, 5, 5); p.curve(7, 5, 9.5, 3.8, 11.24, 2.28);
            p.curve(11.6777, 1.9061, 12.3223, 1.9061, 12.76, 2.28); p.curve(14.51, 3.81, 17, 5, 19, 5);
            p.curve(19.5523, 5, 20, 5.4477, 20, 6); p.close();
            p.move(12, 8); p.line(12, 12);
            p.move(12, 16); p.line(12.01, 16);
        case .shieldCheck:
            p.move(20, 13); p.curve(20, 18, 16.5, 20.5, 12.34, 21.95);
            p.curve(12.1222, 22.0238, 11.8855, 22.0203, 11.67, 21.94); p.curve(7.5, 20.5, 4, 18, 4, 13); p.line(4, 6);
            p.curve(4, 5.4477, 4.4477, 5, 5, 5); p.curve(7, 5, 9.5, 3.8, 11.24, 2.28);
            p.curve(11.6777, 1.9061, 12.3223, 1.9061, 12.76, 2.28); p.curve(14.51, 3.81, 17, 5, 19, 5);
            p.curve(19.5523, 5, 20, 5.4477, 20, 6); p.close();
            p.move(9, 12); p.line(11, 14); p.line(15, 10);
        case .signal:
            p.move(2, 20); p.line(2.01, 20);
            p.move(7, 20); p.line(7, 16);
            p.move(12, 20); p.line(12, 12);
            p.move(17, 20); p.line(17, 8);
            p.move(22, 4); p.line(22, 20);
        case .slidersHorizontal:
            p.move(21, 4); p.line(14, 4);
            p.move(10, 4); p.line(3, 4);
            p.move(21, 12); p.line(12, 12);
            p.move(8, 12); p.line(3, 12);
            p.move(21, 20); p.line(16, 20);
            p.move(12, 20); p.line(3, 20);
            p.move(14, 2); p.line(14, 6);
            p.move(8, 10); p.line(8, 14);
            p.move(16, 18); p.line(16, 22);
        case .smartphone:
            p.move(7, 2); p.line(17, 2); p.curve(18.1046, 2, 19, 2.8954, 19, 4); p.line(19, 20);
            p.curve(19, 21.1046, 18.1046, 22, 17, 22); p.line(7, 22); p.curve(5.8954, 22, 5, 21.1046, 5, 20);
            p.line(5, 4); p.curve(5, 2.8954, 5.8954, 2, 7, 2); p.close();
            p.move(12, 18); p.line(12.01, 18);
        case .sparkles:
            p.move(9.937, 15.5); p.curve(9.7552, 14.7952, 9.2048, 14.2448, 8.5, 14.063); p.line(2.365, 12.481);
            p.curve(2.1499, 12.42, 2.0015, 12.2236, 2.0015, 12); p.curve(2.0015, 11.7764, 2.1499, 11.58, 2.365, 11.519);
            p.line(8.5, 9.936); p.curve(9.2045, 9.7544, 9.7549, 9.2044, 9.937, 8.5); p.line(11.519, 2.365);
            p.curve(11.5794, 2.1491, 11.7763, 1.9998, 12.0005, 1.9998);
            p.curve(12.2247, 1.9998, 12.4216, 2.1491, 12.482, 2.365); p.line(14.063, 8.5);
            p.curve(14.2448, 9.2048, 14.7952, 9.7552, 15.5, 9.937); p.line(21.635, 11.518);
            p.curve(21.8518, 11.5778, 22.002, 11.7751, 22.002, 12);
            p.curve(22.002, 12.2249, 21.8518, 12.4222, 21.635, 12.482); p.line(15.5, 14.063);
            p.curve(14.7952, 14.2448, 14.2448, 14.7952, 14.063, 15.5); p.line(12.481, 21.635);
            p.curve(12.4206, 21.8509, 12.2237, 22.0002, 11.9995, 22.0002);
            p.curve(11.7753, 22.0002, 11.5784, 21.8509, 11.518, 21.635); p.close();
            p.move(20, 3); p.line(20, 7);
            p.move(22, 5); p.line(18, 5);
            p.move(4, 17); p.line(4, 19);
            p.move(5, 18); p.line(3, 18);
        case .squareDashed:
            p.move(5, 3); p.curve(3.8954, 3, 3, 3.8954, 3, 5);
            p.move(19, 3); p.curve(20.1046, 3, 21, 3.8954, 21, 5);
            p.move(21, 19); p.curve(21, 20.1046, 20.1046, 21, 19, 21);
            p.move(5, 21); p.curve(3.8954, 21, 3, 20.1046, 3, 19);
            p.move(9, 3); p.line(10, 3);
            p.move(9, 21); p.line(10, 21);
            p.move(14, 3); p.line(15, 3);
            p.move(14, 21); p.line(15, 21);
            p.move(3, 9); p.line(3, 10);
            p.move(21, 9); p.line(21, 10);
            p.move(3, 14); p.line(3, 15);
            p.move(21, 14); p.line(21, 15);
        case .squarePen:
            p.move(12, 3); p.line(5, 3); p.curve(3.8954, 3, 3, 3.8954, 3, 5); p.line(3, 19);
            p.curve(3, 20.1046, 3.8954, 21, 5, 21); p.line(19, 21); p.curve(20.1046, 21, 21, 20.1046, 21, 19);
            p.line(21, 12);
            p.move(18.375, 2.625); p.curve(19.2034, 1.7966, 20.5466, 1.7966, 21.375, 2.625);
            p.curve(22.2034, 3.4534, 22.2034, 4.7966, 21.375, 5.625); p.line(12.362, 14.639);
            p.curve(12.1245, 14.8762, 11.8312, 15.0499, 11.509, 15.144); p.line(8.636, 15.984);
            p.curve(8.4607, 16.0351, 8.2715, 15.9866, 8.1424, 15.8576);
            p.curve(8.0134, 15.7285, 7.9649, 15.5393, 8.016, 15.364); p.line(8.856, 12.491);
            p.curve(8.9505, 12.1691, 9.1245, 11.8761, 9.362, 11.639); p.close();
        case .sun:
            p.move(16, 12); p.curve(16, 14.2091, 14.2091, 16, 12, 16); p.curve(9.7909, 16, 8, 14.2091, 8, 12);
            p.curve(8, 9.7909, 9.7909, 8, 12, 8); p.curve(14.2091, 8, 16, 9.7909, 16, 12); p.close();
            p.move(12, 2); p.line(12, 4);
            p.move(12, 20); p.line(12, 22);
            p.move(4.93, 4.93); p.line(6.34, 6.34);
            p.move(17.66, 17.66); p.line(19.07, 19.07);
            p.move(2, 12); p.line(4, 12);
            p.move(20, 12); p.line(22, 12);
            p.move(6.34, 17.66); p.line(4.93, 19.07);
            p.move(19.07, 4.93); p.line(17.66, 6.34);
        case .sunMoon:
            p.move(12, 8); p.curve(10.9574, 9.1146, 10.9864, 10.8552, 12.0656, 11.9344);
            p.curve(13.1448, 13.0136, 14.8854, 13.0426, 16, 12); p.curve(16, 14.2091, 14.2091, 16, 12, 16);
            p.curve(9.7909, 16, 8, 14.2091, 8, 12); p.curve(8, 9.7909, 9.7909, 8, 12, 8);
            p.move(12, 2); p.line(12, 4);
            p.move(12, 20); p.line(12, 22);
            p.move(4.9, 4.9); p.line(6.3, 6.3);
            p.move(17.7, 17.7); p.line(19.1, 19.1);
            p.move(2, 12); p.line(4, 12);
            p.move(20, 12); p.line(22, 12);
            p.move(6.3, 17.7); p.line(4.9, 19.1);
            p.move(19.1, 4.9); p.line(17.7, 6.3);
        case .tablet:
            p.move(6, 2); p.line(18, 2); p.curve(19.1046, 2, 20, 2.8954, 20, 4); p.line(20, 20);
            p.curve(20, 21.1046, 19.1046, 22, 18, 22); p.line(6, 22); p.curve(4.8954, 22, 4, 21.1046, 4, 20);
            p.line(4, 4); p.curve(4, 2.8954, 4.8954, 2, 6, 2); p.close();
            p.move(12, 18); p.line(12.01, 18);
        case .tabletSmartphone:
            p.move(5, 8); p.line(11, 8); p.curve(12.1046, 8, 13, 8.8954, 13, 10); p.line(13, 20);
            p.curve(13, 21.1046, 12.1046, 22, 11, 22); p.line(5, 22); p.curve(3.8954, 22, 3, 21.1046, 3, 20);
            p.line(3, 10); p.curve(3, 8.8954, 3.8954, 8, 5, 8); p.close();
            p.move(5, 4); p.curve(5, 2.8954, 5.8954, 2, 7, 2); p.line(19, 2); p.curve(20.1046, 2, 21, 2.8954, 21, 4);
            p.line(21, 20); p.curve(21, 21.1046, 20.1046, 22, 19, 22); p.line(16.6, 22);
            p.move(8, 18); p.line(8.01, 18);
        case .tag:
            p.move(12.586, 2.586); p.curve(12.211, 2.2109, 11.7024, 2.0001, 11.172, 2); p.line(4, 2);
            p.curve(2.8954, 2, 2, 2.8954, 2, 4); p.line(2, 11.172);
            p.curve(2.0001, 11.7024, 2.2109, 12.211, 2.586, 12.586); p.line(11.29, 21.29);
            p.curve(12.2362, 22.2302, 13.7638, 22.2302, 14.71, 21.29); p.line(21.29, 14.71);
            p.curve(22.2302, 13.7638, 22.2302, 12.2362, 21.29, 11.29); p.close();
            p.move(8, 7.5); p.curve(8, 7.7761, 7.7761, 8, 7.5, 8); p.curve(7.2239, 8, 7, 7.7761, 7, 7.5);
            p.curve(7, 7.2239, 7.2239, 7, 7.5, 7); p.curve(7.7761, 7, 8, 7.2239, 8, 7.5); p.close(); p.move(7.495, 7.5);
            p.line(7.505, 7.5);
        case .textCursorInput:
            p.move(5, 4); p.line(6, 4); p.curve(7.6569, 4, 9, 5.3431, 9, 7); p.curve(9, 5.3431, 10.3431, 4, 12, 4);
            p.line(13, 4);
            p.move(13, 20); p.line(12, 20); p.curve(10.3431, 20, 9, 18.6569, 9, 17);
            p.curve(9, 18.6569, 7.6569, 20, 6, 20); p.line(5, 20);
            p.move(5, 16); p.line(4, 16); p.curve(2.8954, 16, 2, 15.1046, 2, 14); p.line(2, 10);
            p.curve(2, 8.8954, 2.8954, 8, 4, 8); p.line(5, 8);
            p.move(13, 8); p.line(20, 8); p.curve(21.1046, 8, 22, 8.8954, 22, 10); p.line(22, 14);
            p.curve(22, 15.1046, 21.1046, 16, 20, 16); p.line(13, 16);
            p.move(9, 7); p.line(9, 17);
        case .toggleRight:
            p.move(8, 6); p.line(16, 6); p.curve(19.3137, 6, 22, 8.6863, 22, 12);
            p.curve(22, 15.3137, 19.3137, 18, 16, 18); p.line(8, 18); p.curve(4.6863, 18, 2, 15.3137, 2, 12);
            p.curve(2, 8.6863, 4.6863, 6, 8, 6); p.close();
            p.move(18, 12); p.curve(18, 13.1046, 17.1046, 14, 16, 14); p.curve(14.8954, 14, 14, 13.1046, 14, 12);
            p.curve(14, 10.8954, 14.8954, 10, 16, 10); p.curve(17.1046, 10, 18, 10.8954, 18, 12); p.close();
        case .touchpad:
            p.move(4, 4); p.line(20, 4); p.curve(21.1046, 4, 22, 4.8954, 22, 6); p.line(22, 18);
            p.curve(22, 19.1046, 21.1046, 20, 20, 20); p.line(4, 20); p.curve(2.8954, 20, 2, 19.1046, 2, 18);
            p.line(2, 6); p.curve(2, 4.8954, 2.8954, 4, 4, 4); p.close();
            p.move(2, 14); p.line(22, 14);
            p.move(12, 20); p.line(12, 14);
        case .trash2:
            p.move(3, 6); p.line(21, 6);
            p.move(19, 6); p.line(19, 20); p.curve(19, 21, 18, 22, 17, 22); p.line(7, 22); p.curve(6, 22, 5, 21, 5, 20);
            p.line(5, 6);
            p.move(8, 6); p.line(8, 4); p.curve(8, 3, 9, 2, 10, 2); p.line(14, 2); p.curve(15, 2, 16, 3, 16, 4);
            p.line(16, 6);
            p.move(10, 11); p.line(10, 17);
            p.move(14, 11); p.line(14, 17);
        case .triangleAlert:
            p.move(21.73, 18); p.line(13.73, 4); p.curve(13.3749, 3.3734, 12.7103, 2.9861, 11.99, 2.9861);
            p.curve(11.2697, 2.9861, 10.6051, 3.3734, 10.25, 4); p.line(2.25, 18);
            p.curve(1.8911, 18.6216, 1.8928, 19.3878, 2.2544, 20.0078);
            p.curve(2.6161, 20.6278, 3.2823, 21.0065, 4, 21); p.line(20, 21);
            p.curve(20.7142, 20.9993, 21.3737, 20.6178, 21.7305, 19.9991);
            p.curve(22.0873, 19.3804, 22.0871, 18.6185, 21.73, 18);
            p.move(12, 9); p.line(12, 13);
            p.move(12, 17); p.line(12.01, 17);
        case .tv:
            p.move(4, 7); p.line(20, 7); p.curve(21.1046, 7, 22, 7.8954, 22, 9); p.line(22, 20);
            p.curve(22, 21.1046, 21.1046, 22, 20, 22); p.line(4, 22); p.curve(2.8954, 22, 2, 21.1046, 2, 20);
            p.line(2, 9); p.curve(2, 7.8954, 2.8954, 7, 4, 7); p.close();
            p.move(17, 2); p.line(12, 7); p.line(7, 2);
        case .type:
            p.move(4, 7); p.line(4, 4); p.line(20, 4); p.line(20, 7);
            p.move(9, 20); p.line(15, 20);
            p.move(12, 4); p.line(12, 20);
        case .undo2:
            p.move(9, 14); p.line(4, 9); p.line(9, 4);
            p.move(4, 9); p.line(14.5, 9); p.curve(17.5376, 9, 20, 11.4624, 20, 14.5);
            p.curve(20, 17.5376, 17.5376, 20, 14.5, 20); p.line(11, 20);
        case .unplug:
            p.move(19, 5); p.line(22, 2);
            p.move(2, 22); p.line(5, 19);
            p.move(6.3, 20.3); p.curve(6.7503, 20.7519, 7.362, 21.0059, 8, 21.0059);
            p.curve(8.638, 21.0059, 9.2497, 20.7519, 9.7, 20.3); p.line(12, 18); p.line(6, 12); p.line(3.7, 14.3);
            p.curve(3.2481, 14.7503, 2.9941, 15.362, 2.9941, 16); p.curve(2.9941, 16.638, 3.2481, 17.2497, 3.7, 17.7);
            p.close();
            p.move(7.5, 13.5); p.line(10, 11);
            p.move(10.5, 16.5); p.line(13, 14);
            p.move(12, 6); p.line(18, 12); p.line(20.3, 9.7); p.curve(20.7519, 9.2497, 21.0059, 8.638, 21.0059, 8);
            p.curve(21.0059, 7.362, 20.7519, 6.7503, 20.3, 6.3); p.line(17.7, 3.7);
            p.curve(17.2497, 3.2481, 16.638, 2.9941, 16, 2.9941); p.curve(15.362, 2.9941, 14.7503, 3.2481, 14.3, 3.7);
            p.close();
        case .user:
            p.move(19, 21); p.line(19, 19); p.curve(19, 16.7909, 17.2091, 15, 15, 15); p.line(9, 15);
            p.curve(6.7909, 15, 5, 16.7909, 5, 19); p.line(5, 21);
            p.move(16, 7); p.curve(16, 9.2091, 14.2091, 11, 12, 11); p.curve(9.7909, 11, 8, 9.2091, 8, 7);
            p.curve(8, 4.7909, 9.7909, 3, 12, 3); p.curve(14.2091, 3, 16, 4.7909, 16, 7); p.close();
        case .users:
            p.move(16, 21); p.line(16, 19); p.curve(16, 16.7909, 14.2091, 15, 12, 15); p.line(6, 15);
            p.curve(3.7909, 15, 2, 16.7909, 2, 19); p.line(2, 21);
            p.move(13, 7); p.curve(13, 9.2091, 11.2091, 11, 9, 11); p.curve(6.7909, 11, 5, 9.2091, 5, 7);
            p.curve(5, 4.7909, 6.7909, 3, 9, 3); p.curve(11.2091, 3, 13, 4.7909, 13, 7); p.close();
            p.move(22, 21); p.line(22, 19); p.curve(21.9986, 17.1771, 20.765, 15.5857, 19, 15.13);
            p.move(16, 3.13); p.curve(17.7699, 3.5832, 19.0078, 5.178, 19.0078, 7.005);
            p.curve(19.0078, 8.832, 17.7699, 10.4268, 16, 10.88);
        case .vibrate:
            p.move(2, 8); p.line(4, 10); p.line(2, 12); p.line(4, 14); p.line(2, 16);
            p.move(22, 8); p.line(20, 10); p.line(22, 12); p.line(20, 14); p.line(22, 16);
            p.move(9, 5); p.line(15, 5); p.curve(15.5523, 5, 16, 5.4477, 16, 6); p.line(16, 18);
            p.curve(16, 18.5523, 15.5523, 19, 15, 19); p.line(9, 19); p.curve(8.4477, 19, 8, 18.5523, 8, 18);
            p.line(8, 6); p.curve(8, 5.4477, 8.4477, 5, 9, 5); p.close();
        case .video:
            p.move(16, 13); p.line(21.223, 16.482); p.curve(21.3764, 16.5841, 21.5735, 16.5935, 21.736, 16.5065);
            p.curve(21.8985, 16.4196, 21.9999, 16.2503, 22, 16.066); p.line(22, 7.87);
            p.curve(22.0001, 7.6909, 21.9043, 7.5255, 21.7491, 7.4363);
            p.curve(21.5938, 7.3471, 21.4027, 7.3477, 21.248, 7.438); p.line(16, 10.5);
            p.move(4, 6); p.line(14, 6); p.curve(15.1046, 6, 16, 6.8954, 16, 8); p.line(16, 16);
            p.curve(16, 17.1046, 15.1046, 18, 14, 18); p.line(4, 18); p.curve(2.8954, 18, 2, 17.1046, 2, 16);
            p.line(2, 8); p.curve(2, 6.8954, 2.8954, 6, 4, 6); p.close();
        case .videoOff:
            p.move(10.66, 6); p.line(14, 6); p.curve(15.1046, 6, 16, 6.8954, 16, 8); p.line(16, 10.5);
            p.line(21.248, 7.438); p.curve(21.4027, 7.3477, 21.5938, 7.3471, 21.7491, 7.4363);
            p.curve(21.9043, 7.5255, 22.0001, 7.6909, 22, 7.87); p.line(22, 16.066);
            p.move(16, 16); p.curve(16, 17.1046, 15.1046, 18, 14, 18); p.line(4, 18);
            p.curve(2.8954, 18, 2, 17.1046, 2, 16); p.line(2, 8); p.curve(2, 6.8954, 2.8954, 6, 4, 6); p.line(6, 6);
            p.move(2, 2); p.line(22, 22);
        case .volume1:
            p.move(11, 4.702); p.curve(10.9996, 4.4172, 10.8278, 4.1606, 10.5647, 4.0516);
            p.curve(10.3015, 3.9427, 9.9986, 4.0028, 9.797, 4.204); p.line(6.413, 7.587);
            p.curve(6.1492, 7.8524, 5.7902, 8.0011, 5.416, 8); p.line(3, 8); p.curve(2.4477, 8, 2, 8.4477, 2, 9);
            p.line(2, 15); p.curve(2, 15.5523, 2.4477, 16, 3, 16); p.line(5.416, 16);
            p.curve(5.7902, 15.9989, 6.1492, 16.1476, 6.413, 16.413); p.line(9.796, 19.797);
            p.curve(9.9976, 19.999, 10.3012, 20.0596, 10.5649, 19.9503);
            p.curve(10.8286, 19.841, 11.0004, 19.5835, 11, 19.298); p.close();
            p.move(16, 9); p.curve(17.3333, 10.7778, 17.3333, 13.2222, 16, 15);
        case .volume2:
            p.move(11, 4.702); p.curve(10.9996, 4.4172, 10.8278, 4.1606, 10.5647, 4.0516);
            p.curve(10.3015, 3.9427, 9.9986, 4.0028, 9.797, 4.204); p.line(6.413, 7.587);
            p.curve(6.1492, 7.8524, 5.7902, 8.0011, 5.416, 8); p.line(3, 8); p.curve(2.4477, 8, 2, 8.4477, 2, 9);
            p.line(2, 15); p.curve(2, 15.5523, 2.4477, 16, 3, 16); p.line(5.416, 16);
            p.curve(5.7902, 15.9989, 6.1492, 16.1476, 6.413, 16.413); p.line(9.796, 19.797);
            p.curve(9.9976, 19.999, 10.3012, 20.0596, 10.5649, 19.9503);
            p.curve(10.8286, 19.841, 11.0004, 19.5835, 11, 19.298); p.close();
            p.move(16, 9); p.curve(17.3333, 10.7778, 17.3333, 13.2222, 16, 15);
            p.move(19.364, 18.364); p.curve(21.0519, 16.6762, 22.0001, 14.387, 22.0001, 12);
            p.curve(22.0001, 9.613, 21.0519, 7.3238, 19.364, 5.636);
        case .volumeX:
            p.move(11, 4.702); p.curve(10.9996, 4.4172, 10.8278, 4.1606, 10.5647, 4.0516);
            p.curve(10.3015, 3.9427, 9.9986, 4.0028, 9.797, 4.204); p.line(6.413, 7.587);
            p.curve(6.1492, 7.8524, 5.7902, 8.0011, 5.416, 8); p.line(3, 8); p.curve(2.4477, 8, 2, 8.4477, 2, 9);
            p.line(2, 15); p.curve(2, 15.5523, 2.4477, 16, 3, 16); p.line(5.416, 16);
            p.curve(5.7902, 15.9989, 6.1492, 16.1476, 6.413, 16.413); p.line(9.796, 19.797);
            p.curve(9.9976, 19.999, 10.3012, 20.0596, 10.5649, 19.9503);
            p.curve(10.8286, 19.841, 11.0004, 19.5835, 11, 19.298); p.close();
            p.move(22, 9); p.line(16, 15);
            p.move(16, 9); p.line(22, 15);
        case .wifi:
            p.move(12, 20); p.line(12.01, 20);
            p.move(2, 8.82); p.curve(7.694, 3.7271, 16.306, 3.7271, 22, 8.82);
            p.move(5, 12.859); p.curve(8.8884, 9.0476, 15.1116, 9.0476, 19, 12.859);
            p.move(8.5, 16.429); p.curve(10.4442, 14.5233, 13.5558, 14.5233, 15.5, 16.429);
        case .wifiHigh:
            p.move(12, 20); p.line(12.01, 20);
            p.move(5, 12.859); p.curve(8.8884, 9.0476, 15.1116, 9.0476, 19, 12.859);
            p.move(8.5, 16.429); p.curve(10.4442, 14.5233, 13.5558, 14.5233, 15.5, 16.429);
        case .wifiOff:
            p.move(12, 20); p.line(12.01, 20);
            p.move(8.5, 16.429); p.curve(10.4442, 14.5233, 13.5558, 14.5233, 15.5, 16.429);
            p.move(5, 12.859); p.curve(6.418, 11.4689, 8.2178, 10.5325, 10.17, 10.169);
            p.move(19, 12.859); p.curve(18.3979, 12.2688, 17.7235, 11.757, 16.993, 11.336);
            p.move(2, 8.82); p.curve(3.2366, 7.7141, 4.6481, 6.821, 6.177, 6.177);
            p.move(22, 8.82); p.curve(18.9172, 6.0628, 14.8327, 4.7008, 10.712, 5.056);
            p.move(2, 2); p.line(22, 22);
        case .x:
            p.move(18, 6); p.line(6, 18);
            p.move(6, 6); p.line(18, 18);
        case .zap:
            p.move(4, 14); p.curve(3.6137, 14.0013, 3.2613, 13.7801, 3.0945, 13.4317);
            p.curve(2.9278, 13.0832, 2.9767, 12.67, 3.22, 12.37); p.line(13.12, 2.17);
            p.curve(13.273, 1.9935, 13.5278, 1.9463, 13.7337, 2.0565);
            p.curve(13.9397, 2.1667, 14.0419, 2.4048, 13.98, 2.63); p.line(12.06, 8.65);
            p.curve(11.9451, 8.9576, 11.9885, 9.302, 12.1761, 9.5714);
            p.curve(12.3637, 9.8409, 12.6717, 10.0011, 13, 10); p.line(20, 10);
            p.curve(20.3863, 9.9987, 20.7387, 10.2199, 20.9055, 10.5683);
            p.curve(21.0722, 10.9168, 21.0233, 11.33, 20.78, 11.63); p.line(10.88, 21.83);
            p.curve(10.727, 22.0065, 10.4722, 22.0537, 10.2663, 21.9435);
            p.curve(10.0603, 21.8333, 9.9581, 21.5952, 10.02, 21.37); p.line(11.94, 15.35);
            p.curve(12.0549, 15.0424, 12.0115, 14.698, 11.8239, 14.4286);
            p.curve(11.6363, 14.1591, 11.3283, 13.9989, 11, 14); p.close();
        }
        return p.finish()
    }
}

private struct RCIconPathBuilder {
    private let path = CGMutablePath()

    func move(_ x: CGFloat, _ y: CGFloat) { path.move(to: CGPoint(x: x, y: y)) }
    func line(_ x: CGFloat, _ y: CGFloat) { path.addLine(to: CGPoint(x: x, y: y)) }
    func quad(_ cx: CGFloat, _ cy: CGFloat, _ x: CGFloat, _ y: CGFloat) {
        path.addQuadCurve(to: CGPoint(x: x, y: y), control: CGPoint(x: cx, y: cy))
    }
    func curve(
        _ c1x: CGFloat, _ c1y: CGFloat, _ c2x: CGFloat, _ c2y: CGFloat, _ x: CGFloat, _ y: CGFloat
    ) {
        path.addCurve(to: CGPoint(x: x, y: y), control1: CGPoint(x: c1x, y: c1y), control2: CGPoint(x: c2x, y: c2y))
    }
    func close() { path.closeSubpath() }
    func finish() -> CGPath { path.copy() ?? path }
}
