// Generated by protocol/generate.mjs. Do not edit.
export const GUEST_PERMISSIONS = [
  {
    "id": "screen.view",
    "label": "View screen",
    "group": "Screen"
  },
  {
    "id": "input.touch",
    "label": "Touch and gestures",
    "group": "Input"
  },
  {
    "id": "input.keyboard",
    "label": "Keyboard",
    "group": "Input"
  },
  {
    "id": "input.button.home",
    "label": "Home button",
    "group": "Device buttons"
  },
  {
    "id": "input.button.lock",
    "label": "Lock button",
    "group": "Device buttons"
  },
  {
    "id": "input.button.volume",
    "label": "Volume buttons",
    "group": "Device buttons"
  },
  {
    "id": "input.button.system_ui",
    "label": "Control Center and notifications",
    "group": "Device buttons"
  }
] as const
export type GuestPermission = typeof GUEST_PERMISSIONS[number]['id']
