import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const protocolDir = dirname(fileURLToPath(import.meta.url))
const root = resolve(protocolDir, '..')
const checkOnly = process.argv.slice(2).includes('--check')

const raw = JSON.parse(await readFile(resolve(protocolDir, 'version.json'), 'utf8'))
const limits = JSON.parse(await readFile(resolve(protocolDir, 'limits.json'), 'utf8'))
if (
  raw.product !== 'rctl' ||
  !Number.isInteger(raw.major) ||
  raw.major < 1 ||
  !Number.isInteger(raw.minor) ||
  raw.minor < 0
) {
  throw new Error('protocol/version.json must contain product rctl and non-negative integer versions')
}

const requiredLimits = [
  'capabilities_json_bytes',
  'signaling_json_bytes',
  'control_json_bytes',
  'file_control_json_bytes',
  'file_chunk_bytes',
  'file_path_utf8_bytes',
  'file_size_integer_max',
  'opus_packet_bytes',
  'features_count',
  'feature_utf8_bytes',
]
for (const name of requiredLimits) {
  if (!Number.isSafeInteger(limits[name]) || limits[name] <= 0) {
    throw new Error(`protocol/limits.json must contain a positive safe integer for ${name}`)
  }
}

const generated = new Map([
  [
    'core/protocol/ProtocolVersion.generated.h',
    `// Generated by protocol/generate.mjs. Do not edit.\n#pragma once\n\n#define RCTL_PROTOCOL_MAJOR ${raw.major}\n#define RCTL_PROTOCOL_MINOR ${raw.minor}\n`,
  ],
  [
    'relay/internal/relay/protocol_version_generated.go',
    `// Code generated by protocol/generate.mjs. DO NOT EDIT.\n\npackage relay\n\nconst (\n\tprotocolMajor = ${raw.major}\n\tprotocolMinor = ${raw.minor}\n)\n`,
  ],
  [
    'mobile/ios/Modules/RctlProtocol/Sources/RctlProtocol/ProtocolVersion.generated.swift',
    `// Generated by protocol/generate.mjs. Do not edit.\n\npublic extension WireProtocolVersion {\n    static let current = WireProtocolVersion(major: ${raw.major}, minor: ${raw.minor})\n}\n`,
  ],
  [
    'mobile/ios/Modules/RctlProtocol/Sources/RctlProtocol/WireLimits.generated.swift',
    `// Generated by protocol/generate.mjs. Do not edit.\n\npublic enum WireLimits {\n    public static let capabilitiesJSONBytes = ${limits.capabilities_json_bytes}\n    public static let signalingJSONBytes = ${limits.signaling_json_bytes}\n    public static let controlJSONBytes = ${limits.control_json_bytes}\n    public static let fileControlJSONBytes = ${limits.file_control_json_bytes}\n    public static let fileChunkBytes = ${limits.file_chunk_bytes}\n    public static let filePathUTF8Bytes = ${limits.file_path_utf8_bytes}\n    public static let fileSizeIntegerMax: UInt64 = ${limits.file_size_integer_max}\n    public static let opusPacketBytes = ${limits.opus_packet_bytes}\n    public static let featuresCount = ${limits.features_count}\n    public static let featureUTF8Bytes = ${limits.feature_utf8_bytes}\n}\n`,
  ],
])

const stale = []
for (const [relativePath, expected] of generated) {
  const path = resolve(root, relativePath)
  if (checkOnly) {
    const actual = await readFile(path, 'utf8').catch(() => '')
    if (actual !== expected) stale.push(relativePath)
    continue
  }
  await writeFile(path, expected)
  process.stdout.write(`generated ${relativePath}\n`)
}

if (stale.length !== 0) {
  process.stderr.write(`generated protocol files are stale:\n${stale.map((path) => `  ${path}`).join('\n')}\n`)
  process.exitCode = 1
}
