import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const protocolDir = dirname(fileURLToPath(import.meta.url))
const root = resolve(protocolDir, '..')
const checkOnly = process.argv.slice(2).includes('--check')

const raw = JSON.parse(await readFile(resolve(protocolDir, 'version.json'), 'utf8'))
if (
  raw.product !== 'rctl' ||
  !Number.isInteger(raw.major) ||
  raw.major < 1 ||
  !Number.isInteger(raw.minor) ||
  raw.minor < 0
) {
  throw new Error('protocol/version.json must contain product rctl and non-negative integer versions')
}

const generated = new Map([
  [
    'core/protocol/ProtocolVersion.generated.h',
    `// Generated by protocol/generate.mjs. Do not edit.\n#pragma once\n\n#define RCTL_PROTOCOL_MAJOR ${raw.major}\n#define RCTL_PROTOCOL_MINOR ${raw.minor}\n`,
  ],
  [
    'relay/internal/relay/protocol_version_generated.go',
    `// Code generated by protocol/generate.mjs. DO NOT EDIT.\n\npackage relay\n\nconst (\n\tprotocolMajor = ${raw.major}\n\tprotocolMinor = ${raw.minor}\n)\n`,
  ],
  [
    'mobile/ios/Modules/RctlProtocol/Sources/RctlProtocol/ProtocolVersion.generated.swift',
    `// Generated by protocol/generate.mjs. Do not edit.\n\npublic extension WireProtocolVersion {\n    static let current = WireProtocolVersion(major: ${raw.major}, minor: ${raw.minor})\n}\n`,
  ],
])

const stale = []
for (const [relativePath, expected] of generated) {
  const path = resolve(root, relativePath)
  if (checkOnly) {
    const actual = await readFile(path, 'utf8').catch(() => '')
    if (actual !== expected) stale.push(relativePath)
    continue
  }
  await writeFile(path, expected)
  process.stdout.write(`generated ${relativePath}\n`)
}

if (stale.length !== 0) {
  process.stderr.write(`generated protocol files are stale:\n${stale.map((path) => `  ${path}`).join('\n')}\n`)
  process.exitCode = 1
}
