// Code generated by protocol/generate.mjs. DO NOT EDIT.

package relay

var guestPermissionIDs = []string{
	"screen.view",
	"input.touch",
	"input.keyboard",
	"input.button.home",
	"input.button.lock",
	"input.button.volume",
	"input.button.system_ui",
}
