// Generated by protocol/generate.mjs. Do not edit.

public enum WireLimits {
    public static let capabilitiesJSONBytes = 65536
    public static let signalingJSONBytes = 262144
    public static let controlJSONBytes = 256
    public static let fileControlJSONBytes = 4096
    public static let fileChunkBytes = 65536
    public static let filePathUTF8Bytes = 1023
    public static let fileSizeIntegerMax: UInt64 = 9007199254740991
    public static let opusPacketBytes = 4000
    public static let featuresCount = 128
    public static let featureUTF8Bytes = 96
}
